### ISSUE TITLE
Auto Select theme from Windows Theme

### ISSUE THREAD

**Issue by amirrammari** [d2phap/ImageGlass#558] opened 2019-07-11 15:16 UTC
Hi, I using ImageGlass.
I changed windows theme to light/dark but app theme not changed.
Please add below feature:
-Auto Select theme from Windows Theme
Thanks.
![Untitled](https://user-images.githubusercontent.com/23485114/61063147-ae2d0d00-a414-11e9-9d75-9fdd573fe934.png)

**Comment by fire-eggs** [comment] 2019-07-13 01:00
Duplicate of issue #434

**Closed** 2019-07-13 01:00 UTC
Labels: ✨ feature request, 📝 duplicate
