### ISSUE TITLE
Shutsdown after a split second of opening an image

### ISSUE THREAD

**Issue by MoneyAllDay** [d2phap/ImageGlass#372] opened 2018-07-09 22:49 UTC
### System information:
 -  Windows 10 Education x64
 - ImageGlass 5.1.5.20

### Describe the bug:
As soon as i open an image ImageGlass just shuts down after a split second, sometimes 2 times in a row, at the 3rd time+- it stays open but if i let sometime pass and i try to view more images the same happens again.

### Expected behavior:
I expect it to not close by itself.

### To Reproduce
1. Open an image.
2. Bam ImageGlass closes.

**Comment by fire-eggs** [comment] 2018-07-12 15:10
I am unable to reproduce the problem.

I have set up Windows 10 x64 Edumacation V1703. I am able to run ImageGlass 5.1.5.20 in both install and portable modes and successfully view images.

What version of Windows 10 are you using? (1511, 1607, 1703)  ImageGlass install or portable? Are there any restrictions for the registry, network, etc? Have you turned off ImageGlass' "check for update"? Did you make ImageGlass the default image viewer?

**Comment by d2phap** [comment] 2018-07-12 16:35
Hi @MoneyAllDay 
Can you try the v5.1.7.2 here: https://imageglass.org/moon
(After downloading, you can extract and override the installed folder)

I wonder if this is thumbnail bar bug which discovered and fixed in Moon version.

**Comment by MoneyAllDay** [comment] 2018-07-12 16:42
I opened at least 30 images and it never closed by itself once. Seems to be working well on v5.1.7.2

As soon as i reverted back to version 5.1.5.20 it closed by itself on the 2nd image i opened.

**Comment by d2phap** [comment] 2018-07-12 16:49
Thanks for your confirmation.
This may be a bug of thumbnail bar while reading meta info of image.

The new official version will be released on the last week of this July.

I will close this issue, if it still persists, feel free to open it again.
Thanks!

**Closed by d2phap** 2018-07-12 16:49 UTC
Labels: ℹ need more information
