### ISSUE TITLE
Image files not updating thumbnail after editing

### ISSUE THREAD

**Issue by UrbanMonk6** [d2phap/ImageGlass#1059] opened 2021-05-16 05:32 UTC
### System information:
 - Windows OS version: Windows 10 20H20 19042.985
 - ImageGlass version:  8.1.4.18

### To Reproduce
1. 
2. 
3. 
4. 

### Actual behavior:

Image files not updating thumbnail after any editing work like cropping..

**Comment by gitflo** [comment] 2021-07-17 04:34
I came across this issue after rotating some photos using ImageGlass June 8.2.6.6 and not seeing the rotation in Windows Explorer's directory listing, even after pressing F5 multiple times.

Then I also came across #754 and found that one to describe my environment's behaviour precisely. I've cross-checked these ways:
* Disabling the option mentioned there, which makes Windows Explorer update its thumbnail
* Using exiftool to analyze the affected files, recognizing that there isn't even any embedded thumbnail present in my JPG photos

Now I'm wondering whether this issue #1059 is just a duplicate of #754 or whether it's describing some other bug. Maybe you can clarify this @UrbanMonk6 

Kind regards
 Florian

**Comment by DCaedus** [comment] 2022-09-05 00:52
Same here, every time after cropping an image with ImgGlass, Windows 11 won't update the thumbnail to reflect the change ever, until I save it again with other editor.

Love the program tho, keep up the good work.

**Comment by d2phap** [comment] 2023-12-14 08:06
Close for now, feel free to ask me to reopen if it still happens on v9

**Closed as completed by d2phap** 2023-12-14 08:06 UTC
Labels: 🐞 bug
