### ISSUE TITLE
Minor bug: ImageGlass shows twice in Installed Apps list

### ISSUE THREAD

**Issue by siblount** [d2phap/ImageGlass#1713] opened 2023-11-25 16:34 UTC
### System information:
 - Windows OS version: 11
 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. Install ImageGlass through classic installer (msi, non-portable)

### Actual behavior:
Two instances of ImageGlass are registered

### Expected behavior:
One instance of ImageGlass is registered

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/74916907/bf28ccd1-1b9c-4fc1-ba23-1fadd8191512)

### Additional context:
Hopefully, this doesn't lead to any issues uninstalling ImageGlass 9 because of this.

**Comment by worldsdream** [comment] 2023-11-25 17:58
It shows for me twice in "Default apps".

**Comment by siblount** [comment] 2023-11-25 19:34
Just realized this could also be because I set it to install in C:/Program Files/ImageGlass instead of local.

**Comment by d2phap** [comment] 2023-11-27 15:54
It seems you installed both MSI and Store version. They are 2 different releases

**Comment by siblount** [comment] 2023-11-27 16:21
@d2phap It was installed using the MSI version from the ImageGlass website choosing the "Get ImageGlass Classic" option, see here:
![image](https://github.com/d2phap/ImageGlass/assets/74916907/09c848e8-536e-4ac1-998e-0f0e4487b336)

I did not install from the Microsoft Store and MSI, just MSI.

**Comment by asjimene** [comment] 2023-11-28 23:02
This issue was caused by the change from a machine based app to a user-based app as referenced by this issue: https://github.com/d2phap/ImageGlass/issues/1708

The apps listed in Add/Remove Programs are stored in the registry in a few different places, for machine-based apps (like the old MSI), they are stored in: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
For user-based apps, they are stored in: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

The new user-based install can not modify the existing machine-based install in the registry (it can replace the files on disk though), so when "upgrading", you'll end up with entries in both the user registry and machine registry area, and will show in Add/Remove Programs as a duplicate.

**Comment by asjimene** [comment] 2023-11-28 23:12
One correction to my earlier comment. The issue is the same, however, for user-based MSI applications, the uninstall entry for both User and Machine-wide installs both exist in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall. However, the issue is the same, the previous version does not get removed because it is a different installation type.

**Comment by DraHD** [comment] 2024-01-14 08:01
![image](https://github.com/d2phap/ImageGlass/assets/75772702/0cc681c1-8fdf-4619-a855-da82cf285148)
This is what happens to the default apps after I uninstall the older MSI version on Windows 11. The active one is the paid version from the Windows app store.

**Comment by worldsdream** [comment] 2024-01-14 13:36
I fixed it by running ccleaner and using their registry tool. 

Perhaps you can fix it with other tools or manually. Let us know.

**Comment by d2phap** [comment] 2024-05-01 02:55
I will just close this for now. The workaround is remove the File Associations of v8 before upgrading to v9 (open IG Settings > File Type Associations > click Unregister extensions)

**Closed as completed by d2phap** 2024-05-01 02:55 UTC
Labels: 🐞 bug
