### ISSUE TITLE
Touchpad support

### ISSUE THREAD

**Issue by amirrammari** [d2phap/ImageGlass#560] opened 2019-07-12 02:00 UTC
![pinch-zoom-in-gesture-icon](https://cdn4.iconfinder.com/data/icons/multitouch-gesture-outline/50/Multitouch_Gesture_Outline-16-128.png)

Please add below feature:
Pinch to zoom on Touchpad

Here are some changes you should make:
1. The `vertical scroll` is zoom; you should change it to `ctrl+vertical scroll`
2. The `ctrl+vertical scroll` is vertical scroll; you should change it to `vertical scroll`
3. The `shift+vertical scroll` is horizontal scroll; you should change it to `horizontal scroll`

Thanks.

**Comment by fire-eggs** [comment] 2019-07-13 00:54
Duplicate of issues 96, 497.

**Comment by fire-eggs** [comment] 2019-07-13 00:55
Just to clarify:

> The vertical scroll is zoom; you should change it to ctrl+vertical scroll
>The ctrl+vertical scroll is vertical scroll; you should change it to vertical scroll
>The shift+vertical scroll is horizontal scroll; you should change it to horizontal scroll

Are you referring to (e.g.) "vertical scroll" via touch interface?

**Comment by amirrammari** [comment] 2019-07-13 01:02
> Just to clarify:
> 
> > The vertical scroll is zoom; you should change it to ctrl+vertical scroll
> > The ctrl+vertical scroll is vertical scroll; you should change it to vertical scroll
> > The shift+vertical scroll is horizontal scroll; you should change it to horizontal scroll
> 
> Are you referring to (e.g.) "vertical scroll" via touch interface?

Yes, I use the touchpad on the laptop.

**Comment by fire-eggs** [comment] 2019-07-13 03:37
Then I think you can control some of these behaviors in the Settings dialog - Image tab. Specifically, the area labelled "Mouse wheel actions". 

Change the "Mouse Wheel" combo from "Zoom" to "Scroll vertically".
Change the "Mouse Wheel + Ctrl" from "Scroll Vertically" to "Zoom".

Not sure how IG receives the touchpad "horizontal scroll" messages.

**Comment by amirrammari** [comment] 2019-07-13 04:04
Ok, thanks.
Now Everything working good.
If you like, set these settings as default settings.

**Comment by fire-eggs** [comment] 2019-07-14 17:33
I'm closing this specific issue.

The touchpad scroll actions appear to us as mouse scrollwheel events; those can be customized. I'll update the FAQ to cover touchpad.

The pinch-to-zoom event is a Windows Touch event, and is covered by issues #96 and #497 .

**Closed by fire-eggs** 2019-07-14 17:33 UTC
Labels: ✨ feature request, 📝 duplicate
