### ISSUE TITLE
Incorrect HiDPI scaling under Windows 8.1 and Windows 10

### ISSUE THREAD

**Issue by lucidfox** [d2phap/ImageGlass#32] opened 2015-07-29 21:11 UTC
If ImageGlass is run under Windows 8.1 or 10 with the scaling factor set to something other than the default 100% (I use 125%), the fonts are blurred. The workaround is to disable DPI scaling in application compatibility properties, but it would be nice if the application worked correctly out of the box.

**Comment by d2phap** [comment] 2015-07-30 13:36
Can you capture your screen? plz!

**Comment by lucidfox** [comment] 2015-07-30 16:16
![ig1](https://cloud.githubusercontent.com/assets/10684/8988453/05e8cc92-3708-11e5-96ab-7611d9530718.png)
![ig2](https://cloud.githubusercontent.com/assets/10684/8988454/0608450e-3708-11e5-81a4-3e58969e9719.png)

**Comment by d2phap** [comment] 2015-08-24 14:47
Fixed!

**Comment by woneob** [comment] 2016-02-07 07:22
I have same problem at v 3.2.0.16 in Windows 10.

![imageglass](https://cloud.githubusercontent.com/assets/1608783/12871281/952bfa9c-cdb6-11e5-8668-e762b54f1e66.png)

**Comment by lucidfox** [comment] 2016-03-13 09:23
That's a different problem, though. It's caused by form layout being fixed and not scaling to font size properly.

**Comment by d2phap** [comment] 2016-03-14 02:23
The issue is at 200% HDPI.  It works on 4K monitors (at 200%) but some of the buttons and settings are hard to work with.
Currently, it supports High DPI at 125%

**Comment by bluemoehre** [comment] 2016-11-21 00:07
Having the same issue in v3.5.9.17 @ 150% scaling.

**Comment by CanisLupus** [comment] 2017-01-02 20:21
Would also like to add that this is what I see at 50% scaling on a 2880x1620 screen. :)

<img width="350" alt="capture" src="https://cloud.githubusercontent.com/assets/532708/21595720/e5768d70-d128-11e6-8100-8cc75f506aa3.PNG">

**Comment by d2phap** [comment] 2017-02-20 15:13
Hi!

Please help me test this issue by downloading and running the ImageGlass.exe in the below link: 
http://www.imageglass.org/upload/moon/ImageGlass_3.x_20022017.zip

Thanks

**Comment by binhnguyenvo** [comment] 2017-02-20 15:35
It looks good for now in regard to 4K-display. Options in settings page get well displayed.
But icons on the toolbar are too tiny and hard to identify.
![aa](https://cloud.githubusercontent.com/assets/19995364/23131537/f001d618-f7bc-11e6-8996-aa896e38778e.PNG)

**Comment by d2phap** [comment] 2017-02-20 15:44
Hi @binhnguyenvo 

Thanks for the screen shot. 
The icons of toolbar will be updated in the final release accordingly.

**Comment by CanisLupus** [comment] 2017-02-20 16:14
Hi @d2phap, nice work! :)

150% scaling on a 2880x1620 screen, Windows 10 (I left the taskbar out of the print):

<img width="1440" alt="image glass" src="https://cloud.githubusercontent.com/assets/532708/23132987/55a47b14-f787-11e6-9d43-4f8786c13ed2.PNG">

Looks perfectly fine now. Icons are still small, but you already mentioned that it will be fixed, so great. Thanks!

**Comment by r-michel** [comment] 2017-02-20 16:17
The update does fixed the issue for me too! Though, I don't know if it's related to how I updated the plugin (extracted the archive to the program folder), but when I open an image (whatever image) I get the following error:

> ImageGlass cannot open this picture because the file appears to be damaged, or corrupted.

**Comment by nZeus** [comment] 2017-02-20 22:11
Cannot run this version. 
It hangs my explorer. Also tried to run it from the command line - still no luck. 
![image](https://cloud.githubusercontent.com/assets/2727326/23143444/c7472afc-f7c1-11e6-97fc-a9adbe7943e7.png)

**Comment by bluemoehre** [comment] 2017-02-20 23:42
Looks fine so far. Only the thumb bar seems to be a little small. I tried to scale it via settings, but it did only enlarge the panel, not the images.

![image-glass-small-thumbs](https://cloud.githubusercontent.com/assets/1735386/23145399/1e858d5c-f7ce-11e6-8892-3532a39edeaf.jpg)

**Comment by d2phap** [comment] 2017-02-22 15:17
Hi @bluemoehre 

Are you able to change the thumbnail dimension in Settings dialog?
You need to restart the app to apply your changes.

![image](https://cloud.githubusercontent.com/assets/3154213/23217620/e518ab70-f954-11e6-99fb-3ff02dc56e0b.png)

**Comment by d2phap** [comment] 2017-02-23 16:38
Hi all,

Here is the latest build:
- Updated HiDPI support for thumbnail bar
- Fixed bug #155 - cannot open image without exifTag

http://www.imageglass.org/upload/moon/ImageGlass_3.x_24022017.zip

Thanks

**Comment by bluemoehre** [comment] 2017-04-01 12:55
@d2phap sorry, was on travel for a while. Could not download that build for testing (404).

**Comment by d2phap** [comment] 2017-04-01 14:45
Hi @lucidfox ,

Please use the latest build.
http://www.imageglass.org/upload/moon/ImageGlass_3.x_31032017.zip

Thanks

**Comment by nZeus** [comment] 2017-04-01 19:28
Hi,

New version is better. And it's not crashing.
But toolbar icons are toooo small. 
See the screenshot:
![image](https://cloud.githubusercontent.com/assets/2727326/24581773/082419f2-1722-11e7-9f21-c0e107febc08.png)

Kind regards, Ilia

**Comment by d2phap** [comment] 2017-04-02 06:17
Hi @nZeus 

Which OS Build of Windows 10 are you using?
Because Microsoft is changing the DPI after the build 14393

Phap

**Comment by bluemoehre** [comment] 2017-04-02 21:32
@d2phap settings looks fine now (I like the additional space within the settings a lot - looks much more structured). Thumbnails are fine too. The toolbar buttons are now in a good size (the icons themselves are still not scaled)

**Comment by d2phap** [comment] 2017-04-03 04:14
Thanks @bluemoehre 
The build b3.5.9.22 also comes with SVG icon set for DPI scaling support but it is still in-progress. :)

Phap

**Comment by d2phap** [comment] 2017-04-06 14:28
HiDPI Scaling is fully supported.
You can try the early version here: http://www.imageglass.org/moon

**Closed by d2phap** 2017-04-06 14:28 UTC
Labels: bug
