### ISSUE TITLE
open EMF utilizes CPU for several seconds

### ISSUE THREAD

**Issue by Luncher91** [d2phap/ImageGlass#240] opened 2017-09-29 11:45 UTC
### Expected behavior:
A EMF file will be displayed and the CPU usage is not significant.

### Actual behavior:
After opening and displaying an EMF file the CPU usage risis up to a full thread and stays there for a couple of seconds (~10 seconds). During that time switching to another image is quite laggy.

### Steps to reproduce:
1. Open a EMF file.
2. Look at the CPU usage

### System info:
- ImageGlass version: 4.1.7.26
- OS version: Windows 10 1607

**Comment by d2phap** [comment] 2018-05-20 02:39
Hi @Luncher91 
Sorry I missed this. 
Can you send me your EMF file to debug?

You mentioned the issue is CPU usage, how about RAM?

**Comment by Luncher91** [comment] 2018-05-20 17:44
Hi @d2phap ,

Thanks for coming back to me. Since I don't use EMF that often anymore I had to create some EMF files. It appears that skipping a larger EMF (fast switching through the images) makes that issue even worse.

[ABC.zip](https://github.com/d2phap/ImageGlass/files/2020518/ABC.zip)

Please have a look at those.

It was a large issue when I posted that issue because I had to scan through many large EMF's.

**Comment by d2phap** [comment] 2018-05-31 02:12
Hi @Luncher91 

Those files are actually large.
Just marked this as limitation. I will work around for further improvement.

**Comment by Luncher91** [comment] 2018-05-31 08:39
Hi @d2phap ,

Thanks for coming back to me. Since I don't use EMF that often anymore I had to create some EMF files. It appears that skipping a larger EMF (fast switching through the images) makes that issue even worse.

[ABC.zip](https://github.com/d2phap/ImageGlass/files/2020518/ABC.zip)

Please have a look at those.

It was a large issue when I posted that issue because I had to scan through many large EMF's.

**Comment by d2phap** [comment] 2023-12-28 11:49
It's been some time, not sure if this still happens with v9. Feel free to ask me reopen it.

**Closed by d2phap** 2023-12-28 11:49 UTC
Labels: 😥 limitation
