### ISSUE TITLE
Option to lock scroll

### ISSUE THREAD

**Issue by nmevenkamp** [d2phap/ImageGlass#1011] opened 2021-04-13 05:42 UTC
### Is your feature request related to a problem? Please describe.
I would like to use the option to lock the zoom to keep the visible portion of an image fixed while scrolling through multiple images of the same dimensions. Essentially, I would like to compare difference in details between multiple images of the same scene. However, currently the image will only keep the zoom ratio fixed, but jump back to the center of the image when going to the next/prev image. 

### Describe the solution you'd like
Add a toggle option (ideally to the toolbar and assigned with a hotkey) that allows to lock the scroll position. With the toggle switched on, the scroll should not jump back to the center when going to the next/prev image, but remain at the same position.

### Describe alternatives you've considered
Except for an image viewer called "feh" available only for Linux, I don't know of any alternative image viewers that have this feature. As a computer vision scientist, I can say that this is a fairly common use case when analyzing image datasets in the context of machine learning.

**Comment by mirh** [comment] 2021-06-08 12:18
This seems a duplicate of #795
If you are doing computer vision stuff though, I wouldn't really use such "normal" tools.

**Comment by fire-eggs** [comment] 2021-06-08 13:39
Great! Thanks!

**Closed as completed by fire-eggs** 2021-06-08 13:39 UTC
Labels: 🎯 feature
