### ISSUE TITLE
Add right click context menu in Windows File Explorer

### ISSUE THREAD

**Issue by MadDogDean** [d2phap/ImageGlass#1093] opened 2021-06-01 06:58 UTC
Just upgraded to a Win 10 laptop from Win 7, and there are lots of "Redmond supplied, built-in frustrations" that come with it. Have used IG for a few years, and happy to bring it for the ride.

I am looking to have the ability to add a right-click context "View in IG" command in Windows File Explorer.

Normally, image files like .png, .psd, I double click to open in my Photoshop for editing, but I would like to be able to have a single click "View in IG".

Currently we can right click > Open with > IG, but I would like to see as a root entry in the right click menu.

I tried to manually add the Registry entries, but for some reason Windows 10 21H1 x64 isn't playing nicely. It doesn't show the entry I created, namely:
```
[HKEY_CLASSES_ROOT\.png\OpenWithIG\command]
@="\"C:\\Program Files\\ImageGlass\\ImageGlass.exe\" \"%1\""
```

Thanks

**Comment by MadDogDean** [comment] 2021-06-01 07:32
OK, don't know why it didn't work earlier, but now the Registry entry works. 
I do think this still would be something good to add to the Options menu in IG to give users this option. Maybe increase user base...

**Comment by fire-eggs** [comment] 2021-06-01 18:33
Duplicate of #1067

**Closed as completed by fire-eggs** 2021-06-01 18:33 UTC

**Comment by tofik7** [comment] 2022-01-04 14:43
Hi,

I tried your register entry to get this feature (Win 10 x64) but it still doesn't work for me,
This is what I added:
[https://i.imgur.com/jc7SfhK.png](url)

Is it correct? I have ImageGlass installed in default folder,

**Comment by MadDogDean** [comment] 2022-01-04 15:38
Try the link provided by @fire-eggs  for Request #1067 

It seems more thorough.

Cheers

**Comment by tofik7** [comment] 2022-01-05 09:17
Thanks for your answer, I tried that and it works for folders but I need it for specific files like you (png, jpeg, etc), still haven't solved that unfortunately.
