### ISSUE TITLE
After 2 - 3 program launches, the toolbar stops drawing.

### ISSUE THREAD

**Issue by spikaspika** [d2phap/ImageGlass#488] opened 2019-01-18 04:52 UTC
Version 6.0.12.29 Portable
Windows 7 pro
After 2 - 3 program launches, the toolbar stops drawing.
With any theme design.
After uninstalling and reinstalling, the panel appears, but then disappears again.

It helped to remove igconfig.xml from drive C.
Although, as I understand it on the C drive, there should not be any in the settings of the programs in the personal profile.
Put on the file attribute "read only", see what happens next.
I'll try to attach a screenshot.

**Comment by d2phap** [comment] 2019-01-18 04:57
Hi @spikaspika 

> With any theme design.

Please specify which theme pack you tried and possibly attach screenshot.
Thank you

**Comment by fire-eggs** [comment] 2019-02-21 15:02
I believe this is a duplicate of #479, where the resource leaks would eventually kill IG. You can test this by turning off "use navigation arrows" and seeing if the problem persists.

If it is the same as #479, then restarting the computer should clear the problem.

You may also have found a new issue, please provide more details (e.g. a copy of your igconfig.xml; how many images being viewed during a session, etc).

**Comment by fire-eggs** [comment] 2019-02-26 21:40
[ImageGlass Moon](https://imageglass.org/upload/moon/ImageGlass_Moon_6.1.0.0.zip) has been updated to 6.1 and should have a fix for #479. Could you try that version and see if your issue still exists?

**Comment by d2phap** [comment] 2019-09-18 16:07
Closed due to no further information provided

**Closed by d2phap** 2019-09-18 16:07 UTC
Labels: ℹ need more information
