### ISSUE TITLE
Relative path for Editor

### ISSUE THREAD

**Issue by alabotski** [d2phap/ImageGlass#1170] opened 2021-11-23 14:19 UTC
I have portable version
Can I use relative path?

Something like in Total Commander
Editor=%COMMANDER_PATH%\..\..\SPSSuite\SyMenuSuite\Notepad++_(x64)_sps\Notepad++.exe "%1"

![image](https://user-images.githubusercontent.com/439337/143040780-7c156b58-4e16-4945-8853-f693e77dbe94.png)

**Comment by d2phap** [comment] 2021-11-24 01:53
It supports relative path, haven't you tried it out?
Something like without `....`
%COMMANDER_PATH%\..\..\SPSSuite\SyMenuSuite\Notepad++_(x64)_sps\Notepad++.exe

**Comment by fire-eggs** [comment] 2021-11-24 02:57
If I understood correctly, the request is for a builtin "macro" like "%COMMANDER_PATH% [e.g. "%IG_PATH%"] to provide the "base" path. From which the relative path is applied.  The value of "%IG_PATH%" being the folder containing the ImageGlass.exe file.

I'm not certain what the point would be, without the OP providing the use-case.

**Comment by alabotski** [comment] 2021-11-24 19:21
Sorry for english
Image Glass is located along this path
d: \ SyMenu \ ProgramFiles \ SPSSuite \ SyMenuSuite \ ImageGlass_ (x64) _sps \

PicPick is located in a different path
d: \ SyMenu \ ProgramFiles \ SPSSuite \ SyMenuSuite \ PicPick_sps \

I want PicPick to be called when editing

What's the "base" path for Image Glass?

![image](https://user-images.githubusercontent.com/439337/143300803-79a887d3-7213-430c-aef7-066ba661dead.png)

**Comment by fire-eggs** [comment] 2021-11-24 23:11
Understood, thank you for the follow up!

No, there isn't a built-in path variable. You can create one in your environment variables and use that. 

For example, one of the pre-defined environment variables is %SystemRoot% and I successfully used it to point to mspaint:

%SystemRoot%\Windows32\mspaint.exe

**Comment by d2phap** [comment] 2021-12-08 13:49
You can use `.\` to get the Startup path of ImageGlass.
Let's say your folder structure is like:
```
D:\Softwares
  |--MS Photos
  |  |--photos.exe
  |
  |--ImageGlass
  |  |--ImageGlass.exe
  |  |--igcmd.exe
```
To get the path of `D:\Softwares\MS Photos\photo.exe`, you can use:
- `".\..\MS Photos\photos.exe"`, or
- `"..\MS Photos\photos.exe"`

**Comment by alabotski** [comment] 2021-12-11 08:32
![image](https://user-images.githubusercontent.com/439337/145670097-530361b7-eaf1-477b-b0e4-a44248ac9a65.png)

**Comment by d2phap** [comment] 2021-12-11 15:21
that's weird, make sure your relative path is correct.
In my test, the folder structure is like this:

```
|--ig\
|  |--ImageGlass.exe
|--net6.0-windows\
|  |--HapplaBox.exe
```


![image](https://user-images.githubusercontent.com/3154213/145681722-43ee10ec-a5cc-453d-97dd-6dcf807ee3f7.png)

![image](https://user-images.githubusercontent.com/3154213/145681737-a906d339-b3d0-49e4-9f49-8b83dc775e17.png)

![image](https://user-images.githubusercontent.com/3154213/145681841-9d64c307-63ec-4f85-b389-5504a93b6406.png)

**Comment by alabotski** [comment] 2021-12-16 07:54
It doesn't work ... = ((

![image](https://user-images.githubusercontent.com/439337/146330148-8e7759b1-6b42-4936-8fb5-376e8bd7872d.png)
![image](https://user-images.githubusercontent.com/439337/146330277-19509f40-bb53-454e-b1ea-ccd97bf2e954.png)
![image](https://user-images.githubusercontent.com/439337/146330381-b947ab20-2c83-4190-9871-dedbf86d5eed.png)

**Comment by d2phap** [comment] 2024-07-20 03:57
I will just close this because I could not reproduce

**Closed as not planned by d2phap** 2024-07-20 03:57 UTC
Labels: ⁉ question
