### ISSUE TITLE
Images with capitalized file extensions do not show thumbnails in W10H 64bit

### ISSUE THREAD

**Issue by BlaqueFlag** [d2phap/ImageGlass#297] opened 2018-01-10 20:10 UTC
### Expected behavior:
All thumbnails to show up in Windows 10 file explorer, instead of the ImageGlass icon.

### Actual behavior:
When an image has a capitalized file type extension, (.PNG or .JPG instead of .png or .jpg) the thumbnails will not be shown.

This is bad because some programs save extensions in capital form by default. 

Attempting to add the file extension via the supported files list was unsuccessful as the editor does not allow you to submit capitalized extensions.

![cap](https://user-images.githubusercontent.com/35310546/34793124-8bdc3648-f607-11e7-9562-8de4db9a99b4.png)

### Steps to reproduce:
1. You can rename image extensions with capitalized extensions and notice that they will not display thumbnails after a refresh.
2.  You can then rename them lower case and refresh and they will appear again.

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10 Home 64bit

**Comment by Phangan** [comment] 2018-01-11 13:07
I have the same OS and ImageGlass version and cannot reproduce this. Works on my system.

**Comment by BlaqueFlag** [comment] 2018-01-16 22:07
@Phangan did you refresh after the rename? It usually won't change without a refresh.

**Comment by d2phap** [comment] 2018-01-17 01:33
Hi @BlaqueFlag 
I also cannot reproduce this. 

![iig](https://user-images.githubusercontent.com/3154213/35020804-d66bc1ea-fb68-11e7-9cef-0089802db0cd.gif)

However, you can try re-registering the files associations of ImageGlass:
- Go to Settings > Files Associations
- Click on Register extensions button
- Open Default App Settings of Windows OS, select ImageGlass as default photo viewer.
http://www.imageglass.org/news/how-to-set-ImageGlass-as-default-photo-viewer

**Comment by Phangan** [comment] 2018-01-17 12:00
@BlaqueFlag yes, I also tried refreshing after capitalizing the extension. Still shows the thumbnail.
Sounds like a Windows issue.

**Comment by BlaqueFlag** [comment] 2018-01-17 16:01
It does seem like a Windows issue. Mine install is a fresh install with the creators update already implemented. Might have something to do with it. 

Would there be any way to register upper case extensions in Image Glass? I have tried to register capitalized ones, but it does not let you add them.

**Comment by d2phap** [comment] 2018-01-23 01:39
Hi @BlaqueFlag 
For my understanding, Windows will consider `jpg` and `JPG` same, I just need to register one of them and actually, we cannot create `jpg` and `JPG` key in registry in the same folder.

I think the issue is due to your Windows OS, not relevant to ImageGlass, I will close this issue.

**Closed by d2phap** 2018-01-23 01:39 UTC
