### ISSUE TITLE
Background and text of Color picker

### ISSUE THREAD

**Issue by DanRotaru** [d2phap/ImageGlass#743] opened 2020-04-16 11:14 UTC
### Description:
The color pallete has a dark background and black text in that, please fix it.

### Screenshots:
![pallete](https://i.ibb.co/s5KNLz7/image.png)

### System information:
 - Windows OS version: Windows 10 (1909) (using light theme)
 - ImageGlass version: 7.5.1.1

**Comment by d2phap** [comment] 2020-04-18 04:24
@DanRotaru 
What are the steps to reproduce? I cannot reproduce this.

**Comment by DanRotaru** [comment] 2020-04-18 15:16
> @DanRotaru
> What are the steps to reproduce? I cannot reproduce this.

I just open it: https://skr.sh/v/180420/eIflOYck.mp4

**Comment by DanRotaru** [comment] 2020-04-18 15:35
Done! I just update config.xml file, change backcolor="#212121" to backcolor="#fffff", and now it's good: ![img](https://i.ibb.co/P5qHNwk/image.png)

**Comment by d2phap** [comment] 2020-04-19 14:27
The text color in theme pack is not correct.

**Comment by d2phap** [comment] 2020-11-19 13:07
Fixed in https://github.com/marnick-s/material-imageglass-themes

**Closed by d2phap** 2020-11-19 13:07 UTC
Labels: Theme, 🐞 bug
