### ISSUE TITLE
Long path / filename (> 256 chars) does not open image

### ISSUE THREAD

**Issue by nikagl** [d2phap/ImageGlass#530] opened 2019-05-21 07:34 UTC
### System information:
 - Windows OS version: Win10 1803, Build 17134.706
 - ImageGlass version: 6.1.5.12

### To Reproduce
1. Create folder path and filename with for instance 245 characters
2. Copy an image file to the path (total path needs to be >256 chars)
3. Open image

### Actual behavior:
ImageGlass screen opens but remains empty

### Expected behavior:
ImageGlass screen opens and shows image

### Screenshots:
Longer than 256 chars:
C:\Temp\This\Is\a\Folder\Structure\With\More\Than\256\Characters\Which\is\quite\difficult\to\create\as\it\requires\many\words\but\when\using\words\it\would\be\achievable\off\course\the\path\may\also\contain\spaces\which\works\fine\with\less\long\ThisIsATestFile.png
![image](https://user-images.githubusercontent.com/1291517/58077080-15180d80-7bac-11e9-9b20-ffe826c3c8a4.png)

Shorter than 256 chars:
C:\Temp\This\Is\a\Folder\Structure\With\More\Than\256\Characters\Which\is\quite\difficult\to\create\as\it\requires\many\words\but\when\using\words\it\would\be\achievable\off\course\the\path\may\also\contain\spaces\which\works\fine\with\ThisIsATestFile.png
![image](https://user-images.githubusercontent.com/1291517/58077022-f44fb800-7bab-11e9-8538-06a77cfc2e5f.png)

### Additional context:
Windows has multiple issues with path's longer than 256 characters (for instance creating a folder >256) but still, it's easily achievable when structuring screenshots of customer environments and such...

**Comment by fire-eggs** [comment] 2019-05-22 01:56
I'm not in a position to dig into this right this instant, but here is a question.

Have you enabled Long Path support on your system? (As described [here](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)).

**Comment by fire-eggs** [comment] 2019-05-22 15:39
There are several dimensions to this - more complex than I expected.

1. I'm not sure how IG is still running for you: I try this and IG consistently dies.
1. I can't drag the _file_ to IG: Windows won't let me. [This might change with Win10 Long Paths enabled].
1. I can't _open_ the file via the File Dialog: Windows won't let me. [This might change with Win10 Long Paths enabled.]
1. The library we are using to load images crashes with a native exception, which causes IG to shut down. [Techie]The library we are using is a managed wrapper around a native library; the managed wrapper is failing to catch the native exception.

So I need to try experiments with Win10 Long Paths enabled, but right now this is looking like a "you can't do that" limitation. I'll need to work with the library author to find out what their plans are for fixing this / supporting Win10 Long Paths. IG also needs to catch native exceptions rather than die ignominiously.

In the meantime, the best workaround I can suggest is to use the `SUBST` command to provide IG with a short path to your various customer environments.  Let me know if you need more detail.

**Comment by nikagl** [comment] 2019-05-23 06:50
> Have you enabled Long Path support on your system? (As described [here](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)).

Yes, tried it (including reboot), but didn't solve the issue...
![image](https://user-images.githubusercontent.com/1291517/58231216-bb901a00-7d36-11e9-909a-af8c06c0545f.png)

1. I open IG using double click on the image file. It simply opens, but does not open the image file (you can see the missing title). Using 64-bit Win10.
2. Same issue
3. It doesn't open for me! I get the following error:
![image](https://user-images.githubusercontent.com/1291517/58231414-407b3380-7d37-11e9-819a-ab2d38fb3704.png)

Drag/drop does work for stuff like command prompt. Not sure what other .net based tool I could use to test this?

Subst works fine, in my case I simply use the Windows Photo Viewer (which I like a lot less than IG!) which works fine, or move it into a smaller TEMP folder and move it back after viewing (in case of a lot of files)...

**Comment by fire-eggs** [comment] 2019-05-24 18:22
Thanks @nikagl for the update!

**Comment by fire-eggs** [comment] 2019-05-24 19:17
Fix is ready, tested on Win10 and Win7 without problems. Allows opening an image by double-clicking. 

Opening a long-file-path image via Open dialog will only work if long path support is enabled on Win10.

Drag-and-drop of file paths longer than 260 characters doesn't work under any circumstances; I'll enter a new issue to cover that case.

**Comment by nikagl** [comment] 2019-05-24 19:36
Superb, let me know when a compiled release is available that I can test. I also noticed a weird bug where all pics in a folder are unreadable when you delete the first picture in a list. Closing IG fixes it (so no files are corrupt)... will create a bug report if it still occurs in next release...

**Comment by d2phap** [comment] 2019-05-25 14:54
Hi @nikagl 
I have just uploaded IG Moon 6.1.5.25. Please help to check.
https://imageglass.org/moon

Thanks

**Comment by nikagl** [comment] 2019-05-26 17:04
Sorry, it didn't work for me after upgrading:
![image](https://user-images.githubusercontent.com/1291517/58384880-c1ad2180-7fe8-11e9-8524-a5596d1a7c04.png)

And win32 long paths is enabled:
![image](https://user-images.githubusercontent.com/1291517/58384897-05079000-7fe9-11e9-84e7-889386110dd1.png)

**Comment by fire-eggs** [comment] 2019-05-27 01:49
Thanks for the update. I messed up.

**Comment by fire-eggs** [comment] 2019-05-27 21:08
Working good for Win10, even with "long path mode" disabled. 

Doesn't work to double-click on a long-path filename in Win7 - so not done yet.

**Comment by fire-eggs** [comment] 2019-05-30 18:35
Works for Win10, agreed to consider the Win7 part as a limitation.  So this particular issue is ready.

**Comment by nikagl** [comment] 2019-05-31 06:41
> Works for Win10, agreed to consider the Win7 part as a limitation. So this particular issue is ready.

No sure how you tested, but Win10 does not work for me (6.1.5.28):
![image](https://user-images.githubusercontent.com/1291517/58686709-d2aab980-837f-11e9-85b3-ff6fc2af20f4.png)

Regards,

Nika.

**Comment by fire-eggs** [comment] 2019-05-31 15:37
Okaaaay, this is starting to have me doubting my sanity.  

All I can tell you at this point is that a) 6.1.5.28 works fine on my dev box, Win10.1803, and b) 6.15.28 fails on another box, Win10.1809.  Either my dev box has something special, or there is a Windows version difference.  Back to debugging ...

To answer your implied question, this is how I'm testing:

![ig_530_Capture](https://user-images.githubusercontent.com/9809727/58714705-486c5080-8393-11e9-8aca-a689332e5546.PNG)

Two cases, double-clicking an image file, with "long path support" ON and OFF:
1. In E:\...\JPG Folder, the folder path is < 240 chars, but the folder+file path exceed 260.
2. In the path ending "New folder longer longer longe", this is the longest folder path Windows Explorer will let me create. Double-clicking on the image shown as selected, the full path is 309 characters.

**Comment by fire-eggs** [comment] 2019-05-31 18:13
OK, here is what is going on.

In my testing, I was always using a long file path from my E:\ drive. Windows gave IG the image path in a useful format and that is the code in IG 6.1.5.28.

However, if the long file path is on the C:\ drive [presumably the boot drive], Windows gives IG the image path in a different format! This format is _not_ consistent with the Windows 10 long path support. It is also the format which is a problem on Windows 7.  

So I will not have a solution in IG for long paths on the C:\ drive any time soon.

The only workarounds I can suggest are:
1. Use a second drive for images.
2. Use the `SUBST` command to create a second drive, mapping part of a long path on C:\ to a virtual drive. I have confirmed this works with IG.  It is possible to persist virtual drives across reboots via the registry.

**Comment by nikagl** [comment] 2019-05-31 19:48
Bizarre! I would have never thought it could be caused by the drive I'm using. Weird stuff. Wonder why other tools (like the default Windows Photo Viewer) do not have an issue, but might just be a .net specific thing... well... at least kudos for trying and thanks for your great tool!

**Comment by d2phap** [comment] 2019-07-10 16:01
Marked this as limitation and looking for help.

**Comment by bucketcat** [comment] 2022-09-13 12:00
Since this is still marked as open nearly half a decade later and I still have the issue I'm going to necro this issue.

Any updates, any workarounds on user end (besides renaming folder or moving deeply nested folders to top directory)?

[I also found this ](https://superuser.com/a/1165879) which could _maybe_ be useful for a future fix in regards to bypassing the 260 char path limit, includes both some janky workarounds and API's that support said functionality.

**Comment by donatopace** [comment] 2022-09-13 16:23
Ti solve the issue
you Need format a partition with "ReFs".
REFs Is a new Microsoft file system.


Il mar 13 set 2022, 14:00 bucketcat ***@***.***> ha scritto:

**Comment by d2phap** [comment] 2022-09-14 02:22
Some people confirm that this issue is resolved in v9.0 beta:
https://groups.google.com/g/imageglass/c/dzlrupO4dp4/m/GH0-zwc3AwAJ

This is probably because v9.0 beta uses .NET 6.0 which supports long path by default: https://github.com/dotnet/runtime/issues/14062#issuecomment-135933052

**Comment by d2phap** [comment] 2022-11-03 16:08
Confirmed this issue is fixed in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904)

**Closed by d2phap** 2022-11-03 16:08 UTC
Labels: 🐞 bug, help wanted, 😥 limitation, v9.0, ✔ v9.0-beta-2/Done
