### ISSUE TITLE
Installer is not removing older version of app when updating to newer version

### ISSUE THREAD

**Issue by krystofkrticka** [d2phap/ImageGlass#1595] opened 2023-06-13 16:07 UTC
### System information:
 - Windows OS version: Windows 11 22H2 Build 22621.1778
 - ImageGlass version: 8.9.6.9

### To Reproduce
1. Install older version of ImageGlass
2. Install newer version of ImageGlass
3. Check appwiz.cpl how many versions of ImageGlass it sees

### Actual behavior:
There are now two version of ImageGlass shown which causes issues when you want to automatically update packages using winget.

### Expected behavior:
Only one version of ImageGlass should be reported in system.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/37749100/30e350b1-5470-4a0e-a548-6e56e59a01e2)

### Additional context:
This issue was discovered after updating manifest in winget repo and updating ImageGlass on computer where was older version installed.

**Comment by d2phap** [comment] 2023-12-05 11:37
Should be fixed for newer versions. I guess it caused by the upgrade code of MSI file. In the recent versions, I used the latest version of Advanced Installer to create MSI file.

**Closed as completed by d2phap** 2023-12-05 11:37 UTC
Labels: 🐞 bug

**Comment by aagha** [comment] 2024-09-04 21:24
How can older versions be removed?
