### ISSUE TITLE
next image takes a second to open and is not immediately opened.

### ISSUE THREAD

**Issue by dante987** [d2phap/ImageGlass#1138] opened 2021-09-13 10:28 UTC
If i have a lot of really big images and i am navigating through them using the arrow keys (next image/previous image), the next image takes a second to open and is not immediately opened. This sometimes may make us think we have not clicked on next image.
In Windows Photo Viewer, the next really big image is immediately opened but just blurred a few milliseconds in the beginning.
Basically it is a bit faster.
Can this feature be added to this software ?

**Comment by fire-eggs** [comment] 2021-09-13 14:23
Duplicate of issue #682 and sort of issue #495

**Closed as completed by fire-eggs** 2021-09-13 14:23 UTC
