### ISSUE TITLE
igcmd - Unhandled exception

### ISSUE THREAD

**Issue by fontgah** [d2phap/ImageGlass#1724] opened 2023-11-26 22:08 UTC
### System information:
 - Windows OS version: 
Windows 11 Enterprise
Version	23H2
OS build	22631.2428 
 - ImageGlass version:  ImageGlass 9.0.7.1125-x64-Official Release.msi

### To Reproduce
Version: igcmd v9.0.7.1125
Release code: kobe
OS: Microsoft Windows NT 10.0.22631.0 64-bit

----------------------------------------------------
Error:

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
----------------------------------------------------

System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs.get__nativeICoreWebView2WebMessageReceivedEventArgs2()
![Uploading Screenshot 2023-11-27 013718.png…]()

**Comment by ruben1PvP** [comment] 2023-11-27 11:42
Your issue seems a duplicate of mine (#1722). I solved it installing WebView2 from [here](https://developer.microsoft.com/en-us/microsoft-edge/webview2).

**Closed as not planned** 2023-11-27 15:14 UTC
Labels: 🐞 bug, 👌🏻 ready

**Comment by EaryChow** [comment] 2023-11-28 16:28
> I solved it installing WebView2 from [here](https://developer.microsoft.com/en-us/microsoft-edge/webview2).


I am having problem with this, how should I do it?
![image](https://github.com/d2phap/ImageGlass/assets/59176246/3e459a39-8e28-4eb4-93ce-ef9c9890cb5a)

**Comment by jtgslol** [comment] 2023-12-09 04:17
Had this exact same issue, it seems be a thing with WebView2 not being installed. If downloading WebView2 from Microsoft and running it doesn't work (as is the case for me), running an app like ClipChamp seems to force install it and it worked for me after. Hopefully this helps if anyone else comes accross this.

**Comment by AblazingHeart** [comment] 2024-01-20 10:13
for anyone that had this issue and would'nt let you install becuase you "alreade have it" I did this and it worked: [https://www.windowsdigitals.com/microsoft-edge-webview2-runtime/](https://www.windowsdigitals.com/microsoft-edge-webview2-runtime/)
