### ISSUE TITLE
Installation problem on Windows Server 2019 X64

### ISSUE THREAD

**Issue by gotspatel** [d2phap/ImageGlass#1711] opened 2023-11-25 11:49 UTC
### System information:
 - Windows OS version:  Windows Server 2019 X64 (Domain Joined)
 - ImageGlass version: ImageGlass_9.0.7.1125_x64

### To Reproduce
1.  Unable to install it says not compatible though the OS is X64 it shows NOT X64
2. 
3. 
4. 

### Additional context:

**Logs as attached**
[MSI61b16.LOG](https://github.com/d2phap/ImageGlass/files/13464042/MSI61b16.LOG)

**Comment by d2phap** [comment] 2023-11-25 13:22
Since IG 9 requires Windows 10 version 2004 or later, when creating the MSI installer, I'm not sure about Windows Server version, so I only checked "Windows Server 2022 x64" in the "Launch Condition" of Advanced Installer

![image](https://github.com/d2phap/ImageGlass/assets/3154213/8fc7ef29-63a9-4a3a-be58-fb26847300b2)

Can you try the portable version and help me check if IG 9 works on your environment?

**Comment by gotspatel** [comment] 2023-11-25 13:32
Update:

1. Portable version 9.0.7.1125 works on Server 2019 x64, also old version msi installer version 8.10.927 works flawlessly
2. the installer version  9.0.7.1125 msi works flawlessly on Server 2022

Please keep the compatibility for server 2019 os for the latest version if possible.

Need more info do let me know.

**Comment by d2phap** [comment] 2023-11-25 13:49
That's good to know!
I will add version 2019 to the list in the future releases.

**Comment by gotspatel** [comment] 2023-11-26 08:02
Eagerly awaiting new version :-D

**Comment by xenadmin** [comment] 2023-11-27 15:32
I just want to add from our perspective:
We install Citrix environments on Windows Server 2016 (Win 10 1607), Windows Server 2019 (Win 10 1809) and Windows Server 2022 (Win 10 21H2)
With the release of v9 we aren't able to install ImageGlass on Server 2016/2019 anymore. 
If it doesn't work on Server anymore, that's sad, but no catastrophe. 
But the missing support for Server 2019, while still being Microsoft supported, is a regression that's an issue for us. 

Since the program is free and free of charge, we do not want to make any claims, so we ask you to question this problem again and perhaps provide support for Server 2016, but definitely for 2019.
Many thanks for the great work on the program!

**Comment by d2phap** [comment] 2023-11-27 15:38
I will remove the OS version check for MSI installer for Windows Server. Also note that, ImageGlass itself requires Windows version 1809 which I cannot verify if it works on Windows Server.

**Comment by d2phap** [comment] 2023-12-05 02:50
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)

**Closed as completed by d2phap** 2023-12-05 02:50 UTC
Labels: 👌🏻 ready, 🛠 improvement

**Comment by RedApple53** [comment] 2024-01-24 04:56
Two Unhandled exception error on server 2019. tried with both .exe and portable one, v1230 / v1208
![image](https://github.com/d2phap/ImageGlass/assets/9291560/6b0cd49c-cf72-4d71-b1d6-fbd5bba1350b)

**Comment by d2phap** [comment] 2024-01-24 05:05
@RedApple53 pls refer to https://github.com/d2phap/ImageGlass/issues/1771#issuecomment-1878380662

**Comment by RedApple53** [comment] 2024-01-24 05:20
Thanks, 1305 portable is working fine on SRV 2019
