### ISSUE TITLE
Image (still) gets corrupted after rotating

### ISSUE THREAD

**Issue by dw-0** [d2phap/ImageGlass#1097] opened 2021-06-14 14:50 UTC
### System information:
 - Windows OS version: Win 10 Pro x64
 - ImageGlass version: 8.2.6.6 x64 Portable

### To Reproduce
1. Open Image with ImageGlass
2. Enable "Save the viewing image after rotating" in the Edit-Settings
2. Rotate the image either left or right
3. Close the window and make ImageGlass save the new orientation
4. File is now corrupted

### Actual behavior:
After describing the behaviour of the earlier version here: https://github.com/d2phap/ImageGlass/issues/1096
The behaviour is almost the same. **But it seems that i can pin down the issue to the auto file saving after rotation.**
EDIT: so basically the bug described here still applies: https://github.com/d2phap/ImageGlass/issues/1033

I closed the other issue after i saw in the changelog, that the issue got fixed and downloaded the newest release. I then immediately tried to rotate the test image and it got corrupted again. 

I then deleted the whole ImageGlass folder where i store my settings too and decided to start over from scratch with a clean "install". After that, rotating worked when i had to save the image manually afterwards. Then i toggled the auto save after rotating. And there we go again... the image got corrupted again.

### Expected behavior:
No corrupted image after saving

### Screenshots:
I recorded my screen again, showing the actual procedure. First with rotating and saving manually. Then toggling the auto-save option which then leads to the file-corruption.
[![Bild bug_still_presenthgjr4.gif auf abload.de](https://abload.de/img/bug_still_presenthgjr4.gif)](https://abload.de/image.php?img=bug_still_presenthgjr4.gif)

**Comment by fire-eggs** [comment] 2021-08-02 17:39
I'm pretty sure, just looking at the GIF and the archive attached to #1096, the problem is due to IG shutting down during the save process. I.e. the same problem as issue #566.

Sometimes your save will succeed, depending on who "wins": app shutdown or save-file.

Ideally, IG should stay running (but invisible) until async tasks like file save finish.

**Comment by d2phap** [comment] 2022-01-12 14:55
Please try the latest build of IG Moon which is to attempts to fix this issue.
https://imageglass.org/moon
Note that, the thumbnail bar is flashing when the app is busy, I will fix later.

**Comment by AndyHarbage** [comment] 2022-03-19 01:20
Still getting this bug. I've just installed ImageGlass 8.5.1.22 (x64). Using Rotate + Auto Save option corrupted several of my large (apprx 100mb) .png files. Including ones I wasn't even rotating. Just navigating through images caused the save message appear erroneously for images I wasn't even changing and corrupt some of my images. Meaning I'm no longer able to open them, as there's only half an image left. 

Windows 11 21H2.

**Comment by SillyCatto** [comment] 2022-07-19 07:09
Im facing the same problem. Enabled "Save the viewing image after rotating" in the Edit-Settings, rotated an image and its corrupted.

Image glass version 8.6.7.13
Windows 10 21H2

![ig](https://user-images.githubusercontent.com/103640580/179688888-b715b097-0df4-4fd2-a818-43236cf84a72.png)

**Comment by Catfriend1** [comment] 2022-10-17 14:22
I also have this problem with the corruption after rotate and pressing left/right cursor keys.
Plus, today I've had three JPG of a book's page. Page 1...3. ImageGlass wrote the content of page3.jpg into page2.jpg. Had a backup copy of the original scans and then noticed, page2.jpg really contained page2 and ImageGlass saved to the wrong file name what was rotated/shown for page 3.

**Comment by Catfriend1** [comment] 2022-11-15 13:02
Thanks for reopening the ticket.

**Comment by masterofobzene** [comment] 2023-02-24 17:57
Is this still happening? it was reported more than two years ago... basic functionality.
The program seems to be having updates, name changes... but this bug is still there?

"qimgv" photo viewer seems to have done this right, why don't you Dev ask him how he did it?

**Comment by Catfriend1** [comment] 2023-02-24 18:02
Yes, the bug is still there.

**Comment by d2phap** [comment] 2023-03-17 16:42
This issue should be fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon.

The saving behaviors are also changed:
- When user make a change to the viewing image, ImageGlass will show a warning message when they want to override it.
- When user make a change to the viewing image and then exit the app, or view another image, ImageGlass will show a prompt to ask user if they want to save the change or not.

![image](https://user-images.githubusercontent.com/3154213/225963268-33deedb8-c2fb-464b-8dce-68a258bff66d.png)


![image](https://user-images.githubusercontent.com/3154213/225963039-a4009770-a590-4a67-bc5e-00d6293810a3.png)

**Comment by Catfriend1** [comment] 2023-03-17 16:52
Good Job! Thank you.

**Comment by masterofobzene** [comment] 2023-03-17 21:25
Why did you include a nag screen instead of just making those warnings on the main page?

**Closed as completed** 2023-03-24 14:43 UTC
Labels: 🐞 bug, 👌🏻 ready
