### ISSUE TITLE
Installation through WinGet Breaks ImageGlass Install

### ISSUE THREAD

**Issue by Aaron2550** [d2phap/ImageGlass#1596] opened 2023-06-14 12:01 UTC
### System information:
 - Windows OS version: Windows 11 Education, 22H2, Build 22621.1778
 - ImageGlass version: 8.8.4.4 -> 8.9.6.9

### To Reproduce
1. Install an older Version through WinGet, in my Example it was 8.8.4.4
2. Wait for a newer Version to release, in my Example its 8.9.6.9
3. Update through WinGet using `winget upgrade`

### Actual behavior:
- WinGet says the Update suceeded, but checking WinGet for Updates still shows the Update from 8.8.4.4 to 8.9.6.9. Trying to install it brings up the Error Message `No installed package found matching input criteria.`
- Trying to open any Image in ImageGlass shows the Error Message `ImageGlass cannot open this picture because the file appears to be damaged, corrupte or not supported. ImageGlass.Heart: The File or Assembly "Magick.NET-Q16-HDRI-OpenMP-x64, Version=13.0.0.0, Culture=neutral, PublicKey=2004825badfa91ec" or a Depedency of it was not found. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`
- Icons inside of the Program are gone

### Expected behavior:
- The Update should not completly Destroy the ImageGlass Installation

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/24834067/eb9cbfe5-4862-42ce-9803-6580bf0d2a89)
![image](https://github.com/d2phap/ImageGlass/assets/24834067/43f3113c-4049-4795-917b-329bcfb12a37)
![image](https://github.com/d2phap/ImageGlass/assets/24834067/caad638b-0b43-476e-b18a-07096719fea6)
![image](https://github.com/d2phap/ImageGlass/assets/24834067/52d08405-0d3e-4179-a513-e610c6365773)

### Additional context:
- I used WingetUI for the screenshots, the same happens when trying to use WinGet through a Terminal

**Comment by chiragwad** [comment] 2023-06-15 14:30
I have the same issue.

**Comment by Telkhine** [comment] 2023-06-16 21:12
Uninstalling ImageGlass, then reinstalling fixed this for me. I had to uninstall two versions actually, as mentioned here in #1595.

**Comment by asheroto** [comment] 2023-09-16 05:22
Looks like this is still happening. Did not install with winget but used Chocolatey to upgrade.

Unfortunately reinstalling does not work, removing the `%AppData%\ImageGlass` folder and recreating does not work. Had to uninstall and remove all folders and reinstall to fix.

**Comment by asheroto** [comment] 2023-09-22 06:55
So.... this has now happened on three computers in the last week. All installed through the command line.

Is this something being looked at? Right now I've just been having to apply workarounds. 😊

**Comment by mackenzieclark** [comment] 2023-10-19 19:42
**edit:** Per Telkhine's comment, there was an older version of Imageglass that was not getting uninstalled. I uninstalled both versions, deleted all files from the installation directory and AppData, reinstalled latest via Chocolatey and it's all good now.

Just uninstall everything and start over and it should work.

|
|
|
|
|
|

I have this same issue since updating from 8.9.6.9 to 8.10.9.27 via chocolatey. Downgrading doesn't fix it, and it looks like it's an issue with Magick.NET. When I reload the image after Imageglass launches, I generate this error:

`System.IO.FileLoadException: Could not load file or assembly 'Magick.NET.Core, Version=13.1.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Magick.NET.Core, Version=13.1.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' ---> System.IO.FileLoadException: Could not load file or assembly 'Magick.NET.Core, Version=13.0.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Magick.NET.Core, Version=13.0.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec'`

Not sure if that helps at all. My UI looks like OP except no error code is displayed, inside the app, instead it crashes:
![image](https://github.com/d2phap/ImageGlass/assets/33103543/8978f3e1-edd4-44cf-99b8-fac5b146be35)

**Comment by asheroto** [comment] 2023-10-21 13:57
I think it should still be considered a bug. This has happened on every computer that I have ImageGlass installed on, so it's not like it's a user-based issue. :-) Reinstalling seems to fix it for now.

**Comment by aly-k** [comment] 2023-10-28 21:54
for anyone still left with imageglass 8.9.6.9 being listed in winget even after uninstalling everything, you might need to delete its registry entry in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

**Comment by d2phap** [comment] 2023-12-05 11:36
Should be fixed for newer versions. I guess it caused by the upgrade code of MSI file. In the recent versions, I used the latest version of Advanced Installer to create MSI file.

**Closed as completed by d2phap** 2023-12-05 11:36 UTC
Labels: 🐞 bug
