### ISSUE TITLE
Too much information in the title bar，simplify information

### ISSUE THREAD

**Issue by bai12-9em** [d2phap/ImageGlass#1154] opened 2021-10-18 23:04 UTC
There is too much information in the title bar. In fact, I don’t need so much information（and it’s not beautiful）,I only need the file name, zoom and number of files.Just like this(2).
@d2phap 

(1)
![图片1 (2)](https://user-images.githubusercontent.com/92163936/137818155-776d23af-5218-4d65-bae8-05df7e220eba.png)
(2)
![图片1 (2) (1)](https://user-images.githubusercontent.com/92163936/137818165-c4c9652f-ebb2-4d35-bfa3-02232add46c3.png)

**Comment by fire-eggs** [comment] 2021-10-19 14:14
Duplicate of issue #971

**Closed as completed by fire-eggs** 2021-10-19 14:14 UTC
Labels: 🎯 feature
