### ISSUE TITLE
Animated PNG Don't Display The Animations

### ISSUE THREAD

**Issue by Eirle** [d2phap/ImageGlass#805] opened 2020-06-25 06:02 UTC
I work a lot with GIF and PNG cause I do animations.
But GIF makes some of my animations really ugly.

ImageGlass only shows the first frame and don't play the animation like the GIFs do.
I use it for all my work because its GUI is really confortable and easy to use.

![rei](https://user-images.githubusercontent.com/67406344/85663625-aef39900-b68f-11ea-946d-69ecd925bb92.png)

**Comment by fire-eggs** [comment] 2020-06-25 16:02
Duplicate of issues #396, #629.

**Closed by fire-eggs** 2020-06-25 16:02 UTC
Labels: ✨ feature request
