### ISSUE TITLE
JPEG XL: Output color mismatch on files with embedded CICP instead of ICC

### ISSUE THREAD

**Issue by kampidh** [d2phap/ImageGlass#1447] opened 2022-11-10 18:02 UTC
Repost of an issue from Magick.NET https://github.com/dlemstra/Magick.NET/issues/1296

### System information:
 - Windows OS version: Windows 10 64 bit 21H2
 - ImageGlass version:  Kobe v8.7.11.6 x64

### To Reproduce
1. Download the [jxldebug.zip](https://github.com/dlemstra/Magick.NET/files/9983225/jxldebug.zip)
2. Open both JXL files on ImageGlass and notice the differences

### Actual behavior:
Color profile from CICP seems to be discarded and not applied properly.

### Expected behavior:
Both images should displayed the same, as both have the same characteristics (Linear Rec.2020).
The only differences is that one uses the CICP values and the other one uses ICC profile.

### Screenshots:
![ig-cicp-icc-2](https://user-images.githubusercontent.com/48910861/201171252-9e48fcab-a411-4cae-83d8-a45b6d041be7.png)

### Additional context:
As stated on the issue from Magick.NET, the conversion from both JXL files to another format yield the same output and the profile from both image is preserved.

**Comment by d2phap** [comment] 2022-11-12 12:05
I can confirm it's the issue with ImageGlass 8. I also tested with version 9 beta 2, the output is quite similar, but the color of the ICC one is more vibrant

**Comment by d2phap** [comment] 2022-11-12 12:12
GIMP also shows the same color as IG 9.0 beta 2.
Can you try and confirm it's correct?

![image](https://user-images.githubusercontent.com/3154213/201473258-c1950694-0253-4bbd-ba39-edd67e9e34a2.png)

**Comment by kampidh** [comment] 2022-11-12 19:34
Tried IG 9.0 beta 2 and GIMP 2.10.32 confirmed that it shows the same as your result.
However it only fixes the TRC / gamma, while the color primaries are still assigned to sRGB, not Rec.2020 (hence the desaturation on IG and GIMP).

AFAIK, the viewer/editor that can currently display image with CICP values correctly are Krita and *(sadly)* Chrome. This seems to be a bug(?) for libjxl lower than version 0.7.0, which perplexed me even more since recent ImageMagick / Magick.NET does ship with libjxl 0.7.0 (hence the JXL decode ability to create the synthetic ICC profile from CICP when converting back to other formats correctly).

**Comment by d2phap** [comment] 2022-11-15 12:43
I downloaded and ran the [MagickViewer](https://github.com/dlemstra/MagickViewer) with the latest version 12.2.1 of Magick.NET, it also shows the same output.

![image](https://user-images.githubusercontent.com/3154213/201921367-522c5d46-2f9f-41ef-b6d9-2a1ad5c1c5dc.png)

**Comment by d2phap** [comment] 2022-12-05 13:11
I will close this because it's upstream issue. I will update the library when they have a fix.

**Closed as not planned by d2phap** 2022-12-05 13:11 UTC
Labels: 🐞 bug, 🐷 upstream issue
