### ISSUE TITLE
Pressing the `Win` key starts zoom (Windows Key). The `Win` should completely be ignored in ImageGlass

### ISSUE THREAD

**Issue by schittli** [d2phap/ImageGlass#1769] opened 2023-12-09 20:42 UTC
### System information:
 - Windows OS version: W10 22H2
 - ImageGlass version: 9.08.1208, x64

### To Reproduce
1. Open an Image in ImageGlass
2. Press the `Win` Key (Windows key) for some seconds: ImageGlass zooms the image as long as you press the key. Extremely annoying
3. Press the `Win` `Tab` (Windows key with the Tab key): ImageGlass starts zooming and does not stop while Windows Displays all active Application Windows (Task-Switch). Extremely annoying

### Actual behavior:
See "Steps to reproduce the behavior:"

### Expected behavior:
1. The `Win` key and any `Win` key combinations **should not do anything in ImageGlass** because those key combinations should be reserved for System tasks
2. It would be very useful if users could modify all keyboard shortcut in ImageGlass

### Screenshots:
-

### Additional context:
-

**Comment by d2phap** [comment] 2023-12-10 11:04
I'm unable to reproduce the issue (Windows 11). Can you attach a video?

**Comment by Otiel** [comment] 2023-12-11 13:18
Same issue here. As soon as I hit the Windows key (even without releasing it), the image gets zoomed out. When I release the Windows key, the zooming out phase stops. If I let the Windows key pressed more than one second, the image is zoomed out to 1% of its original size.

I have the issue since v9.0.7.1125, still happens with v9.0.8.1208.
W10 22H2

https://github.com/d2phap/ImageGlass/assets/3851902/deeb542c-1c51-4a00-bf3c-a494787ea756

**Comment by d2phap** [comment] 2023-12-12 10:56
Thanks for the video, I will test the issue on Windows 10.

**Comment by d2phap** [comment] 2023-12-13 11:21
I tested on VirtualBox, still cannot reproduce

https://github.com/d2phap/ImageGlass/assets/3154213/2b24e376-1ee1-45fb-9a09-b9ae3cba13d1

**Comment by Otiel** [comment] 2023-12-15 22:23
I stopped all software running on my PC to eliminate any conflict that could happen between ImageGlass and other software (especially with software interacting with keystrokes like AutoHotkey & all...), but no luck.

**Comment by ZunRine** [comment] 2024-01-03 00:04
This issue seems like it has to do with the keyboard's input methods for whichever reason.
QWERTY seems to work fine meanwhile AZERTY (french one specifically others work fine) causes the caps lock button to trigger the zoom out function alongside the windows key.
here's an example:

https://github.com/d2phap/ImageGlass/assets/149947245/643b975d-a875-49cf-9004-6edf823b245e


tested on windows 11 pro Version	10.0.22631 Build 22631

**Comment by d2phap** [comment] 2024-01-05 05:20
Thanks @ZunRine for pointing out AZERTY keyboard layout! I managed to reproduce the issue and pushed a fix.

In the meanwhile, you can temporarily fix this by changing the hotkey for menu Zoom Out.
- Close all IG windows
- Open `igconfig.json` file with any text editor (Notepad, VS Code,...)
- Find the `MenuHotkeys` and update it with:
```json
{
  "MenuHotkeys": {
    "MnuZoomOut": ["Subtract"]
  },
}
```
- Save the file and open IG again

**Comment by d2phap** [comment] 2024-01-06 04:20
I created a build for testing this, you can download it here: https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

**Comment by Tomoko1** [comment] 2024-01-06 05:05
> I created a build for testing this, you can download it here: https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

I have an AZERTY keyboard and I can confirm that this bug doesn't happen anymore for me with this build. 🙂👍

**Comment by Otiel** [comment] 2024-01-06 13:09
Looks good to me too, AZERTY keyboard as well. 🥳

**Closed as completed** 2024-01-08 17:12 UTC
Labels: 🐞 bug, 👌🏻 ready
