### ISSUE TITLE
Menu is opened on secondary monitor

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#204] opened 2017-07-05 08:34 UTC
### Expected behavior:
Menu appears on same monitor the window is on

### Actual behavior:
Menu appears on secondary monitor

### Steps to reproduce:
1. Maximimze ImageGlass window
2. Open the menu

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 8

### Other info:
Screenshot (menu is open on second monitor)
![2017-07-05_01-32-06](https://user-images.githubusercontent.com/5490615/27856128-e6da7378-6121-11e7-900a-b4386dea2ad7.png)

**Comment by d2phap** [comment] 2017-07-05 09:00
Thanks @Keith94 
I will investigate time on this

**Comment by d2phap** [comment] 2017-07-16 06:33
I found this link but it only works for submenu.
Seeking for help!
https://stackoverflow.com/questions/26587843/prevent-toolstripmenuitems-from-jumping-to-second-screen

**Comment by RoToRa** [comment] 2018-01-17 10:36
I just run into this issue. As a work-around, would it be possible to have the menu open to the left so that the right side of the menu is aligned with the right side of the window?

**Comment by d2phap** [comment] 2018-01-24 01:51
I'm still doing some sample tests on this and the issue is still open :)

**Comment by kaiyoma** [comment] 2018-02-01 02:00
I just ran into this as well with the latest version of ImageGlass on Windows 10 with an external monitor. Seems like a really odd choice to have the menu be on the right side of the app *and* open to the right. Either the menu should be on the left side of the app or the menu should open to the left, as @RoToRa suggested.

**Comment by d2phap** [comment] 2018-04-03 09:36
This issue is fixed in `develop` branch.
The new build will be update to http://imageglass.org/moon later.

**Closed by d2phap** 2018-04-03 09:36 UTC
Labels: bug, help wanted

**Comment by d2phap** [comment] 2018-04-04 10:12
Fixed the issue caused by this issue: Shortcuts of main menu do not work
