### ISSUE TITLE
Application is broken on 4K screen

### ISSUE THREAD

**Issue by r-michel** [d2phap/ImageGlass#157] opened 2017-02-17 14:31 UTC
On Windows 10, screen resolution: 3200x1800 with W10 zoom at 220%

The toolbar is displayed too small (and there is some empty lines before and after it), and the settings are broken (text line height issue).

![imageglass-bug](https://cloud.githubusercontent.com/assets/25846615/23068967/f2c5306e-f525-11e6-9350-85162920b38a.jpg)

**Comment by d2phap** [comment] 2017-02-17 15:26
Hi @r-michel 

Thanks for your report.
I'm working hard on this issue. I may need your help to test next few days after I finish the fixes.
Please follow up this #32 

Closed as an exact duplicate of #32

**Closed by d2phap** 2017-02-17 15:26 UTC

**Comment by d2phap** [comment] 2017-02-20 15:13
Hi @r-michel 

Please help me test this issue by downloading and running the ImageGlass.exe in the below link: 
http://www.imageglass.org/upload/moon/ImageGlass_3.x_20022017.zip

Thanks
