### ISSUE TITLE
With version 9.0 the PNG image is blurry

### ISSUE THREAD

**Issue by worldsdream** [d2phap/ImageGlass#1716] opened 2023-11-25 17:33 UTC
### System information:
 - Windows OS version: Version 23H2 (Windows 11)
 - ImageGlass version:  9.0.7.1125 (stable)

### To Reproduce
1. Install 9.0.7.1125
2. Open a PNG file
3. It's blurry
4. Remove 9.0.7.1125
5. Install  8.10.9.27 (stable)
6. Open a PNG file
7. Everything looks sharp

I will update with a PNG image or screenshots so you can check.

**Comment by siblount** [comment] 2023-11-25 19:39
@worldsdream 
Is the image in question smaller or larger than your current screen resolution? It's most likely because of the default Image interpolation, since it's default to use a faster, but lower res method of upscaling/downscaling an image.

Try going into your settings, **Layout** -> **Viewer** -> **Zooming**, and set "When zoom <= 100%" and "When zoom > 100%" to **High quality bicubic** and see if it is sharper for you.

**Comment by siblount** [comment] 2023-11-25 20:02
For your reference,

Ranked from fastest & low-res method to slowest & high-res method:

- **Nearest Neighbor** - fastest but produces a low-quality image (blurry or blocky image)
- **Linear** - slightly slower than nearest neighbor but better image quality
- **Multi-sample linear** - slower than linear but better image quality
- **Cubic** - slower than multi-sample but better image quality
- **Anisotropic** - slower than cubic but better image quality
- **High quality bicubic** - slowest method but produces the best image quality.

Because ImageGlass now uses GPU instead of CPU, the speed shouldn't be an issue. But there could be some scenarios where you need to change this setting, especially if you have an older laptop/desktop with only an iGPU (think older than 2016).

For images that are upscaled (aka images that are zoomed in/bigger), my suggestion is to set **When zoom > 100%** to **High quality bicubic**.

For images that are downscaled (aka images that are zoomed out/smaller), my suggestion is to set When zoom <= 100% to **Linear**. 

@d2phap Maybe this calls for a feature improvement...I'm debating whether to create a feature request issue.

**Comment by siblount** [comment] 2023-11-25 20:04
@d2phap The default settings for the zoom options are inversed. To be clear, the default settings for the zoom options should be as described above:

**When zoom > 100%** = **High quality bicubic.**
**When zoom <= 100%** = **Linear**.

**Comment by andrei2987** [comment] 2023-11-28 11:28
> @worldsdream Is the image in question smaller or larger than your current screen resolution? It's most likely because of the default Image interpolation, since it's default to use a faster, but lower res method of upscaling/downscaling an image.
> 
> Try going into your settings, **Layout** -> **Viewer** -> **Zooming**, and set "When zoom <= 100%" and "When zoom > 100%" to **High quality bicubic** and see if it is sharper for you.


It worked for me. Thank you.

**Comment by dabljues** [comment] 2023-11-29 12:52
As mentioned [here](https://github.com/d2phap/ImageGlass/issues/1737#issuecomment-1831825226) (didn't see that that issue was closed), doesn't really work for me.

**Comment by d2phap** [comment] 2023-12-05 02:51
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)

**Closed as completed by d2phap** 2023-12-05 02:51 UTC
Labels: 🐞 bug, 👌🏻 ready

**Comment by vivadavid** [comment] 2023-12-05 11:38
Hi,

I have a similar problem, even in version 9.0.8.1208, but it only affects, so far, a particular PNG. This PNG is a screenshot (taken a long time ago probably with Greenshot).

I've tried different interpolation methods, but nothing changed. (By the way, I couldn't find an interpolation method for those cases when zoom is 100%, but I read in a message above that zoom=100% is included in zoom<100%, so maybe _When zoom < 100%_ could be replaced, in the settings, with _When zoom <= 100%._).

This is the original screenshot:

![original_screenshot](https://github.com/d2phap/ImageGlass/assets/9334287/bdc5e12e-8e06-4cf9-a740-0560b8c722ac)


This is the screenshot image viewed in ImageGlass:

![screenshot_ImageGlass](https://github.com/d2phap/ImageGlass/assets/9334287/0bc96578-1116-40e1-a961-c58644693f67)


This is the screenshot image viewed in Honeyview:

![screenshot_Honeyview](https://github.com/d2phap/ImageGlass/assets/9334287/5b503bd8-da20-4f38-916b-d5faa6cba54a)

**Comment by d2phap** [comment] 2023-12-05 11:47
@vivadavid 
I just tried with IG 8, IG 9 and MS Photos. They all look the same:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/057bf1df-cf44-496b-b7ca-84987296d07f)

**Comment by vivadavid** [comment] 2023-12-05 12:02
Thank you for your reply, @d2phap ! I've just checked that the original screenshot was taken with Greenshot, like the rest of my screenshots, and when I look at the information displayed by ExifTool (see below), I can't find anything different from the information displayed for other screenshots. Maybe there's some kind of rare internal corruption in the PNG due to a bug in Screenshot.

ExifTool Version Number         : 12.70
File Name                       : PEN DRIVE - DUO.png
Directory                       : C:/Users/vivad/Downloads
File Size                       : 16 kB
File Modification Date/Time     : 2023:08:10 11:15:00+02:00
File Access Date/Time           : 2023:12:05 12:49:22+01:00
File Creation Date/Time         : 2023:08:10 11:15:00+02:00
File Permissions                : -rw-rw-rw-
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 359
Image Height                    : 750
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
SRGB Rendering                  : Perceptual
Gamma                           : 2.2
Pixels Per Unit X               : 4724
Pixels Per Unit Y               : 4724
Pixel Units                     : meters
Software                        : Greenshot
Image Size                      : 359x750
Megapixels                      : 0.269

**Comment by vivadavid** [comment] 2023-12-06 09:08
Hi,

I've checked my problematic PNG on other image viewers and only ImageGlass shows a problem.

My screen scale is at 125%, and I've switched to 100% just to give it a try, but the result was the same.

I've viewed a few more images on ImageGlass, but they are all fine, so I really don't know what makes this PNG special.

**Comment by Opicka879** [comment] 2023-12-07 22:32
@vivadavid Try to zoom-out one step and go back to 100% and image should looks fine. I wonder if it behaves the same for you as it does for me. I did report it before the last update and this issue is still same.

Edit: fix works only if i zooming by mouse scroll, not when using auto zoom. And only when zooming out first, not zooming in.

**Comment by vivadavid** [comment] 2023-12-07 23:16
Thanks for your observations, @Opicka879,

With my image at 100%, and using the mouse (with CTRL pressed on):

- Switching to 124% and back to 100% produces a blurry image.
- Switching to 81% and back to 100% produces a fine image. After that, if I go in and out alternatively several times, the image is still fine.

**Comment by Opicka879** [comment] 2023-12-08 19:02
@vivadavid Ok, so it is same like me.

@d2phap Can you look at this again please? :)

**Comment by vivadavid** [comment] 2023-12-08 19:14
The funny thing, @Opicka879, is that I've only detected this behaviour with one image in particular, which was generated by Greenshot, like the rest of my screenshots.

**Comment by d2phap** [comment] 2023-12-23 03:02
@Opicka879 @vivadavid Please help to test the new build: https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868183149

**Comment by vivadavid** [comment] 2023-12-23 09:17
Hi, @d2phap , after your message, you uploaded another build, which is the one I've tested. The file is _IG9_net8.0-windows-17763-x64.zip_, and it contains build 9.0.8.1223.

The problem seems to be fixed: thanks!

As a separate issue, what I've noticed is that, the first time you run this build, the window appears on the right bottom corner:

![image1](https://github.com/d2phap/ImageGlass/assets/9334287/82074e07-b7ad-49ff-9608-347812542848)

**Comment by d2phap** [comment] 2023-12-23 09:23
Thanks @vivadavid for confirming the issue is fixed in build 9.0.8.1223.

> As a separate issue, what I've noticed is that, the first time you run this build, the window appears on the right bottom corner:

I forgot to exclude the `igconfig.json` file when zipping the files.

**Comment by ArchesPatium** [comment] 2024-10-08 08:25
> Hi,
> 
> I have a similar problem, even in version 9.0.8.1208, but it only affects, so far, a particular PNG. This PNG is a screenshot (taken a long time ago probably with Greenshot).
> 
> I've tried different interpolation methods, but nothing changed. (By the way, I couldn't find an interpolation method for those cases when zoom is 100%, but I read in a message above that zoom=100% is included in zoom<100%, so maybe _When zoom < 100%_ could be replaced, in the settings, with _When zoom <= 100%._).
> 
> This is the original screenshot:
> 
> ![original_screenshot](https://private-user-images.githubusercontent.com/9334287/288023884-bdc5e12e-8e06-4cf9-a740-0560b8c722ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzU1MjQsIm5iZiI6MTcyODM3NTIyNCwicGF0aCI6Ii85MzM0Mjg3LzI4ODAyMzg4NC1iZGM1ZTEyZS04ZTA2LTRjZjktYTc0MC0wNTYwYjhjNzIyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDgxMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAyY2VjNDBlMWZjMjdjOTJiNzUzOTI4MTJkNzhiMDM5NmNhM2EzY2I4MWZlZmNlYzA5Y2ZjODU0NGE0NzBkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ohcs2n-6J_4LXt7PNJanN5oHAj4hDOuB7zE-IjvgdV0)
> 
> This is the screenshot image viewed in ImageGlass:
> 
> ![screenshot_ImageGlass](https://private-user-images.githubusercontent.com/9334287/288024061-0bc96578-1116-40e1-a961-c58644693f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzU1MjQsIm5iZiI6MTcyODM3NTIyNCwicGF0aCI6Ii85MzM0Mjg3LzI4ODAyNDA2MS0wYmM5NjU3OC0xMTE2LTQwZTEtYTk2MS1jNTg2NDQ2OTNmNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDgxMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDIzMDNjNGRiYzY5M2I2M2QwZWUxMjE4MmU5NGYwMTQwYmU2MDNiN2U4MTk1OTVlNzZjN2VhNjZjMWNiYWNmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mDB7pkpHS2lHH9_eI0-SLM7lvKve9UUuAoRFeSHfFaI)
> 
> This is the screenshot image viewed in Honeyview:
> 
> ![screenshot_Honeyview](https://private-user-images.githubusercontent.com/9334287/288024112-5b503bd8-da20-4f38-916b-d5faa6cba54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzU1MjQsIm5iZiI6MTcyODM3NTIyNCwicGF0aCI6Ii85MzM0Mjg3LzI4ODAyNDExMi01YjUwM2JkOC1kYTIwLTRmMzgtOTE2Yi1kNWZhYTZjYmE1NGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDgxMzQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE5MWU1ZjE2N2IyYTkwMjdkNzMwZDYyY2FlM2MzYWRmOTFmNzVkZGFhMmJmNzNkOGQwNjFlNDMzNmU4OTAwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pTCZkQ_ddGejEnhF_WjNCOBB8snvR0IUIs8rASiy7mg)

Hey, @vivadavid did you find a fix for that? I'm also having issues with images being low quality. Especially when zooming in.

I tried "High quality bicubic" as well as other combinations of Image Interpolation under Zoom settings and it didn't fix it for me.

Here's an example below. On the left, how it should look, and on the right, how it looks. MS Photos/ImageGlass

![MSPvsIG](https://github.com/user-attachments/assets/a20cb8e9-65b1-4f1b-abcd-25a615e4894f)

**Comment by vivadavid** [comment] 2024-10-08 09:39
Hi, @ArchesPatium ,

They fixed the issue for me a long time ago. The funny thing is that my problem only affected a particular PNG.

**Comment by ArchesPatium** [comment] 2024-10-08 10:42
Oh... I think for me the problem in this specific example might be the Max Image Dimention. Mine has 1903x23936.

But still... That doesn't happen with MS Photos... Would you mind trying to replicate? Just screenshot all of this page:

[https://github.com/bailey27/cppcryptfs?tab=readme-ov-file](url)

If you use firefox it's **control+shift+s** then click on "Save full page" If the image looks the same for you, then the issue might be it.

Edit: Forgot to mention @vivadavid

**Comment by vivadavid** [comment] 2024-10-08 10:48
@ArchesPatium , I don't get any images on your link. If you provide it again, I can check if it's blurry on my PC, but do bear in mind that I'm not a developer, so I can't fix the issue.

**Comment by ArchesPatium** [comment] 2024-10-08 10:56
@vivadavid Sorry about that.

Here's the Image. 

It's okay, by the way. Knowing if the issue happens on other machine other than mine it's good enough.

![Screenshot 2024-10-08 at 07-24-47 bailey27_cppcryptfs cppcryptfs is an implementation of the gocryptfs encrypted overlay filesystem in C for Windows](https://github.com/user-attachments/assets/5822577b-7d7d-4cb7-b8bd-cf58e9c9375e)

**Comment by d2phap** [comment] 2024-10-08 10:59
> Oh... I think for me the problem in this specific example might be the Max Image Dimention. Mine has 1903x23936.

@ArchesPatium, ImageGlass cannot fully load image that is larger than 16,384 x 16,384 pixels, they will be scaled down to fit within these dimensions.

See limitations https://imageglass.org/docs/features

**Comment by ArchesPatium** [comment] 2024-10-08 11:01
@d2phap Oh, sorry for didn't noticing that before. It went over my head.

I appreciate the clarification.

Is there plans to allowing loading larger images? (If at all possible)

**Comment by vivadavid** [comment] 2024-10-08 11:44
@ArchesPatium , I get the same result as you: I can view the image well on Microsoft Photos, but the image is blurry in ImageGlass, though it gets definitely better using cubic.
