### ISSUE TITLE
Faulty Gamma displaying png

### ISSUE THREAD

**Issue by AdrianAtStufish** [d2phap/ImageGlass#503] opened 2019-03-14 13:29 UTC
### System info:
- ImageGlass version: 6.0.12.29
- OS version: _W10

### Expected behavior:
A .jpg, .tif, ,tga, .png saved from the same photoshop file should all look the same

### Actual behavior:
the .png file opens as if the gamma was wrong, although looks OK on the thumbnail strip
![GrabJPG](https://user-images.githubusercontent.com/45972712/54360262-68298d80-465c-11e9-94da-0b070ecbc510.JPG)
![GrabPNG](https://user-images.githubusercontent.com/45972712/54360263-68c22400-465c-11e9-829e-85eb12132d41.JPG)

### Steps to reproduce:
1. ____tell_me_here____
2. ____tell_me_here____
3. ____tell_me_here____

### Other info:
Really cross, we've just managed to persuade the office to stop saving as jpg and use png instead (originals are all tif into .psd) - and now we can't find a quick way to view the png's

**Comment by fire-eggs** [comment] 2019-03-15 16:19
If you could provide us with sample images, it would be helpful.
1) a PSD file; 2) a PNG saved from the PSD file (which shows the wrong gamma).

Thanks!

**Comment by mirh** [comment] 2022-03-19 01:23
Probably duplicate of #377

**Closed** 2023-10-18 10:23 UTC
Labels: ℹ need more information
