### ISSUE TITLE
Sacking/layering behavior suddenly occurs

### ISSUE THREAD

**Issue by CryingNova** [d2phap/ImageGlass#1942] opened 2024-06-15 14:21 UTC
### System information
- Windows OS version: Windows 11 Pro 10.0.22631
- ImageGlass version: 9.1.6.14
- ImageGlass release: Store / Classic? Store

### To Reproduce
1. Open an image within a folder of other images
2. Scroll or click through the images
3. Be met with an odd image stacking/layering behavior

### Actual behavior
I am pixel artist, so I work with many tiny individual files every day, and a significant portion of them having transparency. I've been using this program for many, many months now and only suddenly had this issue. I've noticed that whenever I'm browsing images, the images stack/layer on each other after I've scrolled/clicked through a few? But it has no pattern. Very random and inconsistent. Not all images are affected. It seems to somewhat layer the images from around the image currently focused on the screen. I have tried repairing and reinstalling and both haven't made a difference.

### Expected behavior
I expect to be able to view the singular image that I click on without having several other images attempting to layer itself in the background or on top of it

### Screenshots / Video / Sample image file
The image shows that the current image clicked on and focused on screen also has several other images stacked on top of it in the main viewing window.
![5615](https://github.com/d2phap/ImageGlass/assets/129427247/d94e1840-caa4-4680-a440-9cb9e10084cb)

**Comment by NateUE** [comment] 2024-06-18 22:48
I'm seeing the same issue on version 9.1.6.14
Uninstalled 9.1.6.14 and installed 9.0.11.502 and the issue goes away.

**Comment by d2phap** [comment] 2024-06-24 21:07
@CryingNova Can you send me your `igconfig.json` file? I haven't been able to reproduce it

**Comment by CryingNova** [comment] 2024-07-01 09:29
Sorry for taking a while. Here's my `igconfig.json` from version 9.1
[igconfig.json](https://github.com/user-attachments/files/16050802/igconfig.json)

**Comment by harrywenjie** [comment] 2024-07-05 03:12
Same issue here,  version 9.1.7.627
This seems to occur when images have similar name prefix, for example '1-LYCJSFZJ4.png' '1-LYCJSFZJ5.png' ....
These types of names are common in animation sequence. 
And only on transparent PNG files, obviously if it is opaque image we would not know because one would cover on top of the other. 
Just a wild guess, some kind of buffer is not being clear when changing image. 

=====================

@d2phap Here is a zip file containing some sample images to reproduce the bug. 
[bug_sample.zip](https://github.com/user-attachments/files/16169301/bug_sample.zip)

You can reproduce by using the left and right key while browsing the folder. And they will stack after a few images. 
There is one image in the folder that does not layer with others, probably because it is a different size.

**Comment by d2phap** [comment] 2024-07-12 04:55
I used the `igconfig.json` file from @CryingNova & the sample files from @harrywenjie, but I could not reproduce.

I tested on version 9.1.7.627

https://github.com/user-attachments/assets/5c91d648-9474-4bb2-ba4e-f664c226c10a

**Comment by harrywenjie** [comment] 2024-07-12 08:34
@d2phap Here is my reproduction of the bug:

https://github.com/user-attachments/assets/fbe184f4-fb22-4e09-a43b-01e1d3bc676f


Same version 9.1.7.627, I even cleaned out appdata and reinstalled image glass, the bug remains.

**Comment by d2phap** [comment] 2024-07-12 11:56
Thanks for the video!
I will try to find a way to reproduce the issue on my machine.

**Comment by d2phap** [comment] 2024-07-15 13:53
@harrywenjie 
Can you check if clicking the "Unload image" menu (or press `U`) clears the image?

Try the following steps:
- Open an image
- Click Unload image, then next image
- Check if the next image displayed properly?
- Repeat the above steps

![image](https://github.com/user-attachments/assets/1b395243-addc-43a8-8c87-9eb095fd6463)

**Comment by harrywenjie** [comment] 2024-07-15 23:56
@d2phap I have tried your instructions, Click 'Unload Image'(Or press U) does indeed clear the image from the display. However next image is still layered when immediately clicking on next image or press left or right arrow key. Results are consistent when repeating the steps.

**Comment by d2phap** [comment] 2024-07-18 13:06
@harrywenjie 
Can you help me check if the issue happens on this build?
https://drive.google.com/file/d/1lltfQ5VQN8KXcqKjGDEGUnKoxwRCAGIE/view?usp=sharing

I removed some lines of code for the "View Image Channels" feature which I think is the cause

**Comment by harrywenjie** [comment] 2024-07-18 22:20
@d2phap It is working! Bug is gone in the linked version.

**Comment by d2phap** [comment] 2024-07-19 15:46
@harrywenjie What about this build?
https://drive.google.com/file/d/1TR9JuzDKw9lXQkbrGbxh7hLdK5OyAzy9/view?usp=sharing

**Comment by harrywenjie** [comment] 2024-07-19 21:22
> @harrywenjie What about this build? https://drive.google.com/file/d/1TR9JuzDKw9lXQkbrGbxh7hLdK5OyAzy9/view?usp=sharing

This works fine as well.

**Comment by d2phap** [comment] 2024-07-22 09:13
Fixed in [ImageGlass 9.1.8.723](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.723)

**Closed as completed by d2phap** 2024-07-22 09:13 UTC
Labels: 🐞 bug, 👌🏻 ready
