### ISSUE TITLE
Suggestion: should support high-DPI display with a custom scale.

### ISSUE THREAD

**Issue by binhnguyenvo** [d2phap/ImageGlass#153] opened 2017-01-20 15:33 UTC
The ImageGlass is currently not support high-DPI display. I'm using a 4K-display with scale settings of 250% in Windows 10. But the application does not work well in such a high-DPI display.
   + The icons in toolbar are very tiny and hard to identify.
   + Layout of items in Settings is broken.
Could you consider and support to fix the layout of the app?
Thanks for your great app.

**Comment by d2phap** [comment] 2017-01-21 09:24
Hi @binhnguyenvo ,

Thanks for your feedback.
You can follow up #32 instead.

Closed as an exact duplicate of #32

**Closed by d2phap** 2017-01-21 09:24 UTC

**Comment by d2phap** [comment] 2017-02-20 15:14
Hi @binhnguyenvo 

Please help me test this issue by downloading and running the ImageGlass.exe in the below link: 
http://www.imageglass.org/upload/moon/ImageGlass_3.x_20022017.zip

Thanks
