### ISSUE TITLE
Would you consider adding support for BPG format?

### ISSUE THREAD

**Issue by mmutee** [d2phap/ImageGlass#130] opened 2016-10-01 17:56 UTC
Its been a while since the format surfaced but I still don't see it supported by image viewers.

**Comment by smaragdus** [comment] 2018-08-03 19:10
Support for [BPG](https://bellard.org/bpg/) format would be great since very few image viewers support it (for example- [Simple BPG Image viewer](https://github.com/asimba/pybpgviewer)).

**Comment by fire-eggs** [comment] 2019-12-12 20:20
I have confirmed Imageglass will handle the BPG format today, if the following things are done:
1. Install the BPG tools for Windows ([source](https://bellard.org/bpg/)).
2. Insure the folder containing the BPG tools is in your system PATH.
3. Add "bpg" as a supported format to Imageglass in the Settings dialog, "File Type Associations" tab. Restarting Imageglass will probably be necessary.

The first two steps are required by the library used by ImageGlass to load images.

**Comment by fire-eggs** [comment] 2019-12-12 20:20
Add this to the FAQ and close this issue.

**Comment by d2phap** [comment] 2020-01-05 11:45
updated in support format docs: https://imageglass.org/docs/supported-formats

**Closed by d2phap** 2020-01-05 11:45 UTC
Labels: Documentation, ✨ feature request, 👌 ready
