### ISSUE TITLE
ImageGlass protocol for internet URLs

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#589] opened 2019-07-25 14:34 UTC
ImageGlass protocol is working good for the local address.
```
imageglass:C:\img\iglogo.svg
```
But not working for internet URLs.
```
imageglass:https://imageglass.org/img/iglogo.svg
```
(Sorry for bad English)

**Comment by PrincessRTFM** [comment] 2019-09-28 18:42
It also can't seem to handle network paths, such as those used by WSL. If I try to launch the exe from a Win10 WSL/Ubuntu command line, there is no output and the window does not open, and the executable returns exit code 1.

**Comment by d2phap** [comment] 2019-12-14 17:03
@PrincessRTFM 
Can you share the commands?
Thanks

**Comment by PrincessRTFM** [comment] 2019-12-15 04:26
Actually, the problem turned out to be alias mount points - if I go into an alias-mounted directory and try to call `/mnt/c/Program Files/ImageGlass/ImageGlass.exe`, I get no output and a return value of `1`. For reference, here's how I figured that out:

```sh
cd ~/pics # Aliased to my win10 Pictures folder in /etc/fstab
/mnt/c/Program Files/ImageGlass/ImageGlass.exe
```

No output, immediate exit, status `1`

```sh
cd ~ # Not a mounted directory
/mnt/c/Program Files/ImageGlass/ImageGlass.exe
```

IG opens (although the console waits until it closes - probably what `igcmd.exe` is for??)

So it looks like the problem is in win10's bridging code, not IG. Sorry for the bad report!

**Comment by fire-eggs** [comment] 2019-12-15 19:56
>Actually, the problem turned out to be alias mount points
Interesting. I'll have to give it a try. 

Hopefully the bridging code will be better in WSL2.

**Comment by PrincessRTFM** [comment] 2019-12-16 05:12
Just to put it on the record here, apparently _none_ of my native windows applications can launch properly within an aliased mount point, which suggests that WSL's bridging doesn't like having "virtual" working directories. Every program I try - web browsers, notepad++, ImageGlass, VLC, etc - gives the same effect, which is immediate termination with no output and an exit code of `1`. In case it matters, I'm using WSL-Ubuntu from the windows app store. I can't see the shell mattering, but it's `zsh` and I'm using it through a GNU `screen` session in the [mintty/wsltty](https://github.com/mintty/wsltty/releases) terminal.

**Comment by d2phap** [comment] 2023-12-28 11:32
I will close this as not planned

**Closed by d2phap** 2023-12-28 11:32 UTC
Labels: ✨ feature request
