### ISSUE TITLE
Associating .ico files with ImageGlass stops them from being displayed in Explorer

### ISSUE THREAD

**Issue by jernejs** [d2phap/ImageGlass#664] opened 2019-12-20 12:06 UTC
### System information:
 - Windows OS version: Windows 10 x64 1903
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. During first startup choose to associate image files with ImageGlass

### Actual behavior:

Icon files display ImageGlass icon instead of showing the actual icon. Annoyingly, this also affects some shortcuts that use na .ico file for their icon.

### Expected behavior:

Icon files show their content in Explorer

**Comment by d2phap** [comment] 2020-02-09 03:25
Hi @jernejs 

Can you check if this option is unchecked?
![image](https://user-images.githubusercontent.com/3154213/74095649-d3ab0200-4b2e-11ea-98a2-86832a69ae4f.png)

**Comment by sknxis** [comment] 2020-04-21 16:06
Hi, I'm experiencing this issue as well. That option is unchecked for me.

Windows version: **10 Pro (64-bit) 1909**
ImageGlass version: **7.5.11**

![image](https://user-images.githubusercontent.com/63120874/79887067-be204700-83bf-11ea-9fce-6ff9244747d2.png)

**Comment by bughunter2** [comment] 2020-08-23 19:19
I came here just to report this workaround for people looking for one:
(I tested this in a Windows 7 virtual machine.)

What worked for me is to remove the (whole) 'UserChoice' registry key here:

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ico\UserChoice`

After that, you can restart the Windows Explorer via the Task Manager (or log off and log on again).
Or run this command: `taskkill /f /im explorer.exe && explorer.exe`

Hopefully this helps.

If that didn't help, then you may wish to inspect the following other registry keys against those of a clean Windows installation:

**( Keep these: )**

```
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.ico
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ico
HKEY_CLASSES_ROOT\icofile
HKEY_CLASSES_ROOT\.ico
```

**Comment by xantao** [comment] 2021-02-04 13:45
> 
> 
> I came here just to report this workaround for people looking for one:
> (I tested this in a Windows 7 virtual machine.)
> 
> What worked for me is to remove the (whole) `UserChoice` registry key here:
> 
> `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ico\UserChoice`
> 
> (You may have to change the Permissions and remove the ACL 'Deny' entry so you can actually remove it. On a clean installation this key doesn't exist, so it's safe to do so.)
> 
> After that, you can restart the Windows Explorer via the Task Manager (or log off and log on again).
> Or run this command: `taskkill /f /im explorer.exe && explorer.exe`
> 
> Hopefully this helps.
> 
> If that didn't help, then you may wish to inspect the following other registry keys against those of a clean Windows installation:
> 
> **( Keep these: )**
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.ico
> HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ico
> HKEY_CLASSES_ROOT\icofile
> HKEY_CLASSES_ROOT\.ico
> ```

This sadly didnt work for me at all on a 3 week old Windows 10 installation. Not after uninstalling ImageGlass, nor deleting the registry key tree, nor using DISM to check Windows integrity.

No one knows whats causing this?

**Comment by bughunter2** [comment] 2021-02-05 23:51
Without knowing exactly what you are experiencing, I think the following may be helpful.

A method is described to clear the Windows Explorer thumbnail caches. That may (or may not) resolve your issue.

Steps:
1. First, make sure to follow the first workaround, [posted above](https://github.com/d2phap/ImageGlass/issues/664#issuecomment-678813537), to remove the `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ico\UserChoice` registry key.
2. Next, run these 3 commands manually in a `cmd.exe` command prompt:
IMPORTANT: All Windows Explorer windows will be closed by the first command below.
```
taskkill /f /im explorer.exe
del /f "%LocalAppData%\Microsoft\Windows\Explorer\thumbcache*"
explorer.exe
```
3. Hopefully the issue is now resolved.

**Comment by nvire** [comment] 2021-02-06 00:06
> Without knowing exactly what you are experiencing, I think the following may be helpful.
> 
> A method is described to clear the Windows Explorer thumbnail caches. That may (or may not) resolve your issue.
> 
> Steps:
> 
>     1. First, make sure to follow the first workaround, [posted above](https://github.com/d2phap/ImageGlass/issues/664#issuecomment-678813537), to remove the `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.ico\UserChoice` registry key.
> 
>     2. Next, run these 3 commands manually in a `cmd.exe` command prompt:
>        IMPORTANT: All Windows Explorer windows will be closed by the first command below.
> 
> 
> ```
> taskkill /f /im explorer.exe
> del /f "%LocalAppData%\Microsoft\Windows\Explorer\thumbcache*"
> explorer.exe
> ```
> 
>     1. Hopefully the issue is now resolved.

I gave this a shot but no dice still. Really odd.

Thanks a bunch for your help so far though, I appreciate it

**Comment by davecarrijo** [comment] 2022-01-20 11:32
Dev, please can u fix it? Every time I put your program with mais image view. It happens.

**Comment by davecarrijo** [comment] 2022-01-21 06:02
> 

First  save the olds reg. them...

To me, this looks more like a Windows issue than a ImageGlass issue, tbh.
I've tested with several programs, and every program I've tested that registers itself as the default viewer for ICO files triggers this problem.

The solution, for me at least, was to remove the "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\ImageGlass.AssocFile.ICO" and "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.ico\PersistentHandler" registry keys.

Start cmd or powershell as administrator and run the following commands, then restart your machine:
REG DELETE HKLM\SOFTWARE\Classes\ImageGlass.AssocFile.ICO /f
REG DELETE "HKLM\SOFTWARE\Classes\.ico\PersistentHandler" /ve /f

ImageGlass will no longer be the default viewer for ICO files, and the taskbar/startmenu icons should return to normal.

This is what solved it for me, but your results may vary.

**Comment by davecarrijo** [comment] 2022-01-21 07:18
Or this, worked for me after trying all available solution on all well-known websites

then I tried
update 1: Python Repair Tool
Update 2: Google Drive File Stream
although I don't have used this app before

My Solution :

1: Enable Windows Administrator Account

Select “Start” and type “CMD“.
Right-click “Command Prompt” then choose “Run as administrator“.
If prompted, enter a username and password that grants admin rights to the computer.
Type: net user administrator /active:yes.
Press “Enter

2: sign out then sign in to that user

3: check if Search Icons working ex. calculator

4: open run WINDOWS + R

5; put

%LocalAppData%\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache

and hit ok

6: found folder with name 100 or 125 or 150 etc then take a copy and paste it in C:\

7: log out this login in your normal user

8:take a copy from C:\

9: open run WINDOWS + R

10; put

%LocalAppData%\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache

and hit ok

11: paste it accept overwrite

12: it should work now

13: Select “Start” and type “CMD“.
Right-click “Command Prompt” then choose “Run as administrator“.
If prompted, enter a username and password that grants admin rights to the computer.
Type: net user administrator /active:no
Press “Enter“.
Replace “yes” with “no” to disable the admin account on the welcome screen.

**Comment by d2phap** [comment] 2022-01-21 07:32
In v8.4, ImageGlass ignores `.ICO` extension to avoid this issue

**Closed** 2022-01-21 07:33 UTC
Labels: 🐞 bug

**Comment by DimMan88** [comment] 2022-01-26 15:23
Finaly **problem solved**.

After tried E-V-E-R-Y-T-H-I-N-G how to solve this issue........

**Its not an .ico issue.**

UWP apps have .PNG icons located in their package folder inside WindowsApps folder...

**1.** You must change the permissions in the WindowsApps folder to TrustedInstaller and follow these commands here: 

**https://www.winhelponline.com/blog/windowsapps-folder-restore-default-permissions/**

**2.** Change from 100% scaling to 125% and see if icons now showing up.

**3.** Change back to 100% scaling.

So....
**NOT** an Imageglass issue.

**Comment by cakiya** [comment] 2022-07-13 08:34
> Finaly **problem solved**.
> 
> After tried E-V-E-R-Y-T-H-I-N-G how to solve this issue........
> 
> **Its not an .ico issue.**
> 
> UWP apps have .PNG icons located in their package folder inside WindowsApps folder...
> 
> **1.** You must change the permissions in the WindowsApps folder to TrustedInstaller and follow these commands here:
> 
> **https://www.winhelponline.com/blog/windowsapps-folder-restore-default-permissions/**
> 
> **2.** Change from 100% scaling to 125% and see if icons now showing up.
> 
> **3.** Change back to 100% scaling.
> 
> So.... **NOT** an Imageglass issue.

the link: step 3 asks me to input this into command prompt (admin):
`icacls "%programfiles%\WindowsApps" /setowner "nt service\trustedinstaller"`
but my output is 
`C:\Program Files\WindowsApps: Access is denied.
Successfully processed 0 files; Failed processing 1 files`
while the website says i should expect
`processed file: WindowsApps
Successfully processed 1 files; Failed processing 0 files`
...so what do i do now, i tried going to 125% scaling despite the error and the icons are still hijacked, going back to 100% also still hijacked
also just restarted computer and tried the website steps again, same output for step3

edit: ok doing davecarrijo's method worked, hopefully this issue only applies to older versions  and that a fresh install of a version past v8.4 doesn't need icon fixing :)

**Comment by sovalyeler** [comment] 2022-07-13 09:27
Don't follow that "solution". It's going to break some of the apps.

**Comment by cakiya** [comment] 2022-07-27 02:14
ok nvm i guess it just decided to revert the fix after a while, its bugged again.

i uninstalled imageglass, restarted computer and its still using imageglass png file type icon...? if its uninstalled how is it still being hijacked by imageglass png icon

edit: deleting the files in AppIconCache in davecarrijo's solution doesn't fix the icons but it turns all the broken imageglass icons into broken windows photo viewer icons

**Comment by cakiya** [comment] 2022-07-27 03:56
ok i finally fixed it, in my case it was because of the Google Drive application. uninstall it by going to system settings apps and uninstall it

https://appuals.com/fix-icons-not-showing-correctly-in-windows-10-search/

in the comments there are steps:

Serdar Sağlam
Friends, the source of this problem is the Google Drive program. Surprising to see that it still causes the same issue.

I guess they don't fix this on purpose, they sabotage the Windows system.

1. Uninstall Google Drive
2. Windows Display Settings, change your scale setting from 100% > 150% > 175% > 100%.
3. Restart computer

and this FINALLY worked, i'll install imageglass again and restart my computer to see if imageglass hijacks my icons again ill edit this message

final edit (hopefully): installed imageglass, restarted computer and no more broken icons! google sucks

**Comment by TheRealSamChaney** [comment] 2022-12-01 06:22
**This issue is not resolved so please re-open this ticket**. It is **not** caused by Google Drive application as I uninstalled that and rebooted and the icons are **still** broken (still showing the ImageGlass PNG default image). I have tried every suggested fix:

1. Using the "Unregister extensions" option in Imageglass (which is broken and gives an error in Windows)
2. Deleting the registry keys associating ImageGlass with .ico and .png files
3. Uninstalling ImageGlass completely
4. Deleting every file and folder everywhere in my computer with "Imageglass" in the name
5. Changing the display settings zoom
6. Uninstalling Google Drive

I rebooted between every one of these steps and **still** the icons in my start menu are broken. Please find the root cause to this bug and fix it!

**Comment by DimMan88** [comment] 2023-03-04 18:42
where is the .reg download?

**Comment by davecarrijo** [comment] 2023-03-04 22:33
> where is the .reg download?
 
You can literaly just copy past it brodar.
