### ISSUE TITLE
Win Server 2019 - unhandled exception 

### ISSUE THREAD

**Issue by fisics** [d2phap/ImageGlass#1771] opened 2023-12-11 05:16 UTC
### System information:
 - Windows OS version:  Server 2019
 - ImageGlass version:  9.0.8.1208

### To Reproduce
Just Start IG

### Actual behavior:
IG9 doesn't start.

Application: ImageGlass.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (0xC000000D): Unknown error (0xc000000d)
   at DirectN.VerticalBlankTicker.Wait(Object state)

**Comment by d2phap** [comment] 2023-12-12 10:54
I'm not using Windows Server so I can't check this but other people could run it normally [#1711](https://github.com/d2phap/ImageGlass/issues/1711#issuecomment-1826313259).

You may check your event viewer to see the detail of the error because when googling `0xC000000D`, all results are about "Your PC needs to be repaired" issue. It seems some files are missing or corrupted.

**Comment by CaptainKey3s** [comment] 2023-12-19 13:04
We have the same issue with image glas 9.

### System information:
Windows OS version: Server 2019
ImageGlass version: 9.0.8.1208

### Steps to reproduce the behavior:
Start Image Glas

### Actual behavior:
Image Glas doesn't start. It just shows the following error message.

Version: ImageGlass v9.0.8.1208
Release code: kobe
OS: Microsoft Windows NT 10.0.17763.0 64-bit

----------------------------------------------------
Error:

Unknown error (0xc000000d)
----------------------------------------------------

System.ComponentModel.Win32Exception (0xC000000D): Unknown error (0xc000000d)
   at DirectN.VerticalBlankTicker.Wait(Object state)


### Evenviewer Log:
Application: ImageGlass.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (0xC000000D): Unknown error (0xc000000d)
   at DirectN.VerticalBlankTicker.Wait(Object state)

and

Name der fehlerhaften Anwendung: ImageGlass.exe, Version: 9.0.8.1208, Zeitstempel: 0x65410000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.17763.4974, Zeitstempel: 0x909c5ed9
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00000000000349b9
ID des fehlerhaften Prozesses: 0xe0a4
Startzeit der fehlerhaften Anwendung: 0x01da327706a36819
Pfad der fehlerhaften Anwendung: C:\Program Files\ImageGlass\ImageGlass.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 2cb9b50d-d03f-4ab1-9400-1aa6dfe14d45
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Ferdi-SQ** [comment] 2023-12-19 14:40
Hi, we are getting the same error message on Windows server 2019 X64.

### System Information

Windows OS: Windows Server 2019 X64
Version 1809 Build 17763.5206

### **Eventviewer errors:**

**.NET Runtime**

Application: ImageGlass.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (0xC000000D): Unknown error (0xc000000d)
   at DirectN.VerticalBlankTicker.Wait(Object state)

**Application Error**

Faulting application name: ImageGlass.exe, version: 9.0.8.1208, time stamp: 0x65410000
Faulting module name: KERNELBASE.dll, version: 10.0.17763.4974, time stamp: 0x909c5ed9
Exception code: 0xe0434352
Fault offset: 0x00000000000349b9
Faulting process id: 0x294c
Faulting application start time: 0x01da3287bee13e58
Faulting application path: C:\Program Files\ImageGlass\ImageGlass.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ec300f1e-6b84-4085-966e-c8cc093ff081
Faulting package full name: 
Faulting package-relative application ID:

**Comment by d2phap** [comment] 2023-12-19 15:15
I think I found the issue, your OS version is `10.0.17763.4974`. IG 9.0 is built against Windows `10.0.19041.0`.

I would say your Windows version is not supported but I also try lowering the Windows SDK version.
Can you help to check if this build works for you?
https://drive.google.com/file/d/11NCGDcztDXh-rpjaRRBrcCwtwX45AIM-/view?usp=sharing

**Comment by Ferdi-SQ** [comment] 2023-12-19 15:37
Hi, thanks for your prompt response.
This version also generates the same error.

Am I right to believe this version is not supported for Windows server 2019?

**Comment by CaptainKey3s** [comment] 2023-12-19 15:48
This Version generates the same error for me too

**Comment by fisics** [comment] 2023-12-19 15:53
here too.

**Comment by d2phap** [comment] 2023-12-20 16:54
Thanks for the info.
Can you try this build?
https://drive.google.com/file/d/1lF6c0ZY7K9BL6iAAQ6E6BtqtgVl0gbwd/view?usp=sharing

I just tried suppressing the error.

**Comment by Ferdi-SQ** [comment] 2023-12-21 10:28
Hi, this version produces the same error.
What is odd, is that some users get the error, and some don't.

for instance, my testuser has no issues, my admin user has no issues. But users cannot start the software.
User profiles have already been reset, to no avail.

**Comment by d2phap** [comment] 2023-12-29 13:48
Can you try [v9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230) if the issue still persists?

**Comment by Ferdi-SQ** [comment] 2024-01-02 14:56
Same issue on version 9.0.9.1230

**Comment by smeyernyc** [comment] 2024-01-03 21:25
Same issue for me 9.0.9.1230 server 2019 1809 build 17763.5206

**Comment by d2phap** [comment] 2024-01-05 09:36
Can you check if this build fix the issue?
https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

I replaced the entire `VerticalBlankTicker` with `PeriodicTimer` which caused the issue on some monitors. `VerticalBlankTicker` is in charge of ticking system for frame animation like smooth zooming & panning, image fading transition,...

**Comment by 6Fxx** [comment] 2024-01-05 10:53
Hello,

It works perfectly for me on a 2022 server.

Good job, thanks

**Comment by Ferdi-SQ** [comment] 2024-01-08 16:06
Issue has not been resolved on server 2019. I keep getting the same error message.

**Comment by 6Fxx** [comment] 2024-01-08 16:19
> Issue has not been resolved on server 2019. I keep getting the same error message.

It works with version 1305.

![Capture d’écran du 2024-01-08 17-17-06](https://github.com/d2phap/ImageGlass/assets/155731714/b6445811-2f70-41a5-8bd0-2827ac1ea244)

**Comment by RedApple53** [comment] 2024-01-24 05:23
1305 portable is working fine on SRV 2019

**Comment by d2phap** [comment] 2024-01-31 13:12
This issue is fixed in [ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201)

**Closed as completed by d2phap** 2024-01-31 13:12 UTC
Labels: 🐞 bug, 👌🏻 ready
