### ISSUE TITLE
Some shortcuts do not display Latin script letters in English (and other Latin languages)

### ISSUE THREAD

**Issue by aethior** [d2phap/ImageGlass#1999] opened 2024-09-01 23:54 UTC
### System information
- Windows OS version: Windows 10 Pro, Version 22H2
- ImageGlass version: 9.1.8.723 (64-bit)
- ImageGlass release: Classic Installed

### To Reproduce
1. Set English language
2. Go to Main menu
3. Go to Image menu
4. Check the 'Flip Horizontal' and 'Flip Vertical' shortcuts

### Actual behavior
The shortcuts display Asian (?) characters.

### Expected behavior
The shortcuts should display Latin characters.

### Screenshots / Video / Sample image file
![screenshot](https://github.com/user-attachments/assets/5903dd7a-39f8-48e7-8ccc-64518b1d0da6)

**Comment by d2phap** [comment] 2024-09-11 02:35
Hi @aethior,
What language are you using for your Windows?

**Comment by aethior** [comment] 2024-09-11 14:15
Hi @d2phap,

Español (España)

Regards.

![spanish](https://github.com/user-attachments/assets/3881726c-a98e-4660-b2df-f8bd9e821d51)

**Comment by AmeJunn** [comment] 2024-09-28 07:31
I can confirm with pt-br it also has this visual bug. The hotkey still works as intended. It's only visual.
![Captura de tela 2024-09-28 043044](https://github.com/user-attachments/assets/bb502df7-c481-4102-93e7-c96424427d34)

**Comment by d2phap** [comment] 2024-11-04 15:00
Should be fixed in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104)

**Closed as completed by d2phap** 2024-11-04 15:00 UTC
Labels: 👌🏻 ready, 🛠 improvement
