### ISSUE TITLE
First Launch Configuration - Infinite loop

### ISSUE THREAD

**Issue by mcj123** [d2phap/ImageGlass#346] opened 2018-05-19 06:52 UTC
### System info:
- ImageGlass version: 5.0.5.7
- OS version: Windows 10

### Expected behavior:
complete configuration box

### Actual behavior:
Configuration box keeps popping back up

### Steps to reproduce:
1. install new version
2. Launch program

**Comment by d2phap** [comment] 2018-05-19 07:06
@mcj123 
Can you edit your issue?
Please add Steps to reproduce to help me understand your issue
Thanks

**Comment by mcj123** [comment] 2018-05-19 07:09
Hi,
Just after installing the update, the program pops up configuration
box called first launch configurations, and I go through it.  It never
launches the program, but keeps coming up with first launch
configurations...
Those are the steps..
Mike
 Sent using Hushmail
On 5/19/2018 at 2:06 AM, "Phap Dieu Duong"  wrote:

	@mcj123
 Can you edit your issue?
 Please add Steps to reproduce to help me understand your issue
 Thanks

**Comment by d2phap** [comment] 2018-05-31 01:01
- Were you opening any ImageGlass windows in that time?
- portable version or installer version? 

Thanks

**Comment by mcj123** [comment] 2018-05-31 03:01
NopeInstaller Version
 Sent using Hushmail
On 5/30/2018 at 8:01 PM, "Phap Dieu Duong"  wrote:

 	*Were you opening any ImageGlass windows in that time? 	*portable
version or installer version? 
	Thanks

**Comment by fire-eggs** [comment] 2018-06-21 01:04
From google group: tony...@gmail.com:

> On the latest version of ImageGlass 5.1.5.20 in 32bit Windows 10 ONLY, the first launch configurations gets stuck in a loop. 
I have tried a clean install, and also a different PC (32 bits as well), but it has the same problem. 64bit works ok.

**Comment by fire-eggs** [comment] 2018-06-28 21:11
I have reproduced this issue on Win10-32Bit and IG 5.1.5.20 (install). After completing first-launch, my registry settings are:

![image](https://user-images.githubusercontent.com/9809727/42060258-3964a054-7af4-11e8-97b9-6c30f7075344.png)

With a version of IG in place which has some logging, I find:
1. ImageGlass.exe believes the folder "C:\program files\ImageGlass" is writable, and thus IsPortableMode is true.
1. ImageGlass.exe pulls the settings from igconfig.xml, and first_launch_version is 0.
1. igcmd.exe on the other hand writes the settings to the registry.

**Comment by fire-eggs** [comment] 2018-06-28 21:53
The discrepancy between ImageGlass and igcmd (at least on 32-bit windows) is the app.manifest settings.

In the app.manifest files, igcmd is configured to "asInvoker". ImageGlass is not. If I set ImageGlass to "asInvoker", it correctly sets  IsPortableMode to false.

**Comment by fire-eggs** [comment] 2018-06-29 18:36
Fixed.

**Comment by d2phap** [comment] 2018-07-02 13:06
Hi @mcj123 
Can you help to test the latest build and confirm?
https://imageglass.org/moon

Thanks

**Comment by mcj123** [comment] 2018-07-02 13:13
Is there an installer?
 Sent using Hushmail
On 7/2/2018 at 8:06 AM, "Phap Dieu Duong"  wrote:

	Hi @mcj123
 Can you help to test the latest build and confirm?
 https://imageglass.org/moon 

	Thanks

**Comment by d2phap** [comment] 2018-07-02 13:14
Hi @mcj123 
Because this is not official release, I will just provide the zip version.
You can extract and override to the current installed folder.

**Comment by mcj123** [comment] 2018-07-03 05:50
Phap,
I have reinstalled the original problem version, and it seems to be
OK.  I have also launched the program from the file you sent, and it
is OK as well.
Hope this helps.
Mike J
 Sent using Hushmail
On 7/2/2018 at 8:15 AM, "Phap Dieu Duong"  wrote:

	Hi @mcj123
 Because this is not official release, I will just provide the zip
version.
 You can extract and override to the current installed folder.

**Comment by d2phap** [comment] 2018-07-03 06:29
Thanks for the confirmation!

**Comment by mcj123** [comment] 2018-07-03 06:37
I'm sorry, Phap.  I just launched the 5.0.5.7 version with same
result.(Infinite loop).  Did you say I should copy the files directly
into the ImageGlass folder?
 Sent using Hushmail
On 7/3/2018 at 1:29 AM, "Phap Dieu Duong"  wrote:

	Thanks for the confirmation!

**Comment by d2phap** [comment] 2018-07-03 06:53
Can you try the v5.1.7.2 from this link https://imageglass.org/moon?
> Did you say I should copy the files directly into the ImageGlass folder?

Yes. You can extract the zip file and override to ImageGlass folder.

**Comment by fire-eggs** [comment] 2018-07-11 01:16
Confirmed fixed in Google groups.

**Closed by fire-eggs** 2018-07-11 01:16 UTC
Labels: 🐞 bug, 👌 ready
