### ISSUE TITLE
Ability to navigate between images in a zip file without extracting

### ISSUE THREAD

**Issue by MCD4U** [d2phap/ImageGlass#960] opened 2021-01-08 08:31 UTC
### Is your feature request related to a problem? Please describe.
Back when I used windows photo viewer, when I opened a zip file (without extracting it) with lots of images in them, I could open one of the images and still be able to navigate to previous or next images in the current folder/zip file, **without** needing to extract the zip file. I wish to have this feature in ImageGlass as well.

### Describe the solution you'd like
Being able to navigate to previous or next images while in a zip file. For example using the arrow keys would bring me to the previous/next image in the current folder.

### Describe alternatives you've considered
One alternative would be to  extract the zip file and then view the images. Extracting often takes time, especially if the zip file contains more than just the images I want to view, I would still need to extract the whole thing. I believe having this feature would save time.

**Comment by fire-eggs** [comment] 2021-01-08 18:26
Duplicate of issue #254.

**Closed as completed by fire-eggs** 2021-01-08 18:26 UTC
