### ISSUE TITLE
One problem when ImageGlass opens huge pictures

### ISSUE THREAD

**Issue by 265785** [d2phap/ImageGlass#733] opened 2020-04-11 03:36 UTC
ImageGlass will crashes (more than 40 seconds) when opening huge pictures created by the new version of Photoshop. and I sincerely hope you can fix it.
Thank you!

### System information:
Windows OS version: Windows 10 x64 家庭中文版 1909
ImageGlass version: 7.5.4.4

### To Reproduce
when opening huge pictures created by the new version of Photoshop.

### Actual behavior:

ImageGlass will crashes (more than 40 seconds) when opening the picture. Especially JPEG images. 

### Screenshots:

![20200411110323](https://user-images.githubusercontent.com/56037874/79034404-3761b200-7be8-11ea-981c-d5a6ac53a13a.png)
![0_3](https://user-images.githubusercontent.com/56037874/79034431-5bbd8e80-7be8-11ea-97ee-d1289385f0a0.jpeg)
![0_1](https://user-images.githubusercontent.com/56037874/79034441-75f76c80-7be8-11ea-9c67-82c11576473d.jpeg)
![搜狗截图20200411111806](https://user-images.githubusercontent.com/56037874/79034451-80b20180-7be8-11ea-9476-c9f2ba442bb8.png)

**Comment by d2phap** [comment] 2020-04-11 03:43
@265785 can u attach the sample image file please?

**Comment by d2phap** [comment] 2020-04-11 03:52
Also, there is a limit for image size in ImageGlass https://github.com/d2phap/ImageGlass/issues/272#issuecomment-348381055

Your image size is 18400 x 10350, which is too large to open in ImageGlass (at the moment)

**Comment by 265785** [comment] 2020-04-11 03:52
链接：https://pan.baidu.com/s/1RoO8edm8xh1u4Qe44ZrJJw 
提取码：zk3j

**Comment by d2phap** [comment] 2020-04-11 04:04
> 链接：https://pan.baidu.com/s/1RoO8edm8xh1u4Qe44ZrJJw
> 提取码：zk3j

It's required me to register an account to be able to download the file which I don't like to do.
I think the problem is that the image size is too big for ImageGlass to open. This is a limitation, there is no fix for this, at least in the near future.

**Comment by 265785** [comment] 2020-04-11 04:33
https://user-images.githubusercontent.com/56037874/79035367-57956f00-7bf0-11ea-8a93-60e196faf361.jpg
This file also loads slowly (have that problem). Though it loads faster than the previous picture.

**Comment by d2phap** [comment] 2020-04-11 04:47
@265785 
It's known issue in v7.5 (https://github.com/d2phap/ImageGlass/issues/720) due to external library we are using.
To temporarily fix this, you can disabled Color management in Settings > Image > Color management, under Color profile dropdown box, select `None`

**Comment by 265785** [comment] 2020-04-11 05:02
Thank you very much!

**Comment by d2phap** [comment] 2020-04-11 07:29
Close this, please refer to #272 for update in the future

**Closed by d2phap** 2020-04-11 07:29 UTC
Labels: 🐞 bug
