### ISSUE TITLE
The image will move automatically follow the mouse after Win+Shift+LeftClick if scale out of viewport.

### ISSUE THREAD

**Issue by suyangzuo** [d2phap/ImageGlass#1839] opened 2024-02-04 12:26 UTC
### System information:
 - Windows OS version: Windows11 23H2
 - ImageGlass version: 9.0.10.201

### To Reproduce
1. scale the image out of the viewport
2. hold Win+Shift and left click the image
3. image will move follow the mouse automatically

**Comment by d2phap** [comment] 2024-08-25 07:21
This issue should be fixed in v9.1 already, cannot reproduce anymore

**Closed as completed by d2phap** 2024-08-25 07:21 UTC
Labels: 🐞 bug
