### ISSUE TITLE
Hidden settings in the UI

### ISSUE THREAD

**Issue by Shituation** [d2phap/ImageGlass#1266] opened 2022-01-23 21:46 UTC
### System information:
 - Windows OS version:  WIN 10 x64
 - ImageGlass version:  8 5 1 22

### To Reproduce
1. Go to settings
2. Go to "image" on the left side.
3. Scroll down to "Slideshow"

### Actual behavior:
![image](https://user-images.githubusercontent.com/43975882/150699131-4bb00168-6f06-48aa-a7dc-13e497086897.png)

**Comment by fire-eggs** [comment] 2022-01-24 15:53
I don't see the issue with IG 8.5.1.22 (which supercedes 8.4.x, that release has been withdrawn).

If you still see the problem after upgrading to 8.5.1.22, we'll probably need to know more about your system (esp. the monitors - HD, resolution, etc).

**Comment by Shituation** [comment] 2022-01-24 15:55
Try setting your res to 3840 x 2160 and scale at %200.
Corrected the version, it was 8.5.1.22.

**Comment by fire-eggs** [comment] 2022-01-24 16:22
Yup, I see it now ...

There's a little glitch in the tools panel as well:

![image](https://user-images.githubusercontent.com/9809727/150822701-e96d5623-9aae-439d-b8bf-4e5522bcb81f.png)

**Comment by fire-eggs** [comment] 2022-01-24 19:13
The Scale at 200% is what causes the issue.

**Comment by fire-eggs** [comment] 2022-01-24 19:35
I think the problem is caused by using "Percent" instead of "Autosize" or "Absolute" for the `tableLayoutPanel2` container in frmSetting.

Not sure what's going on in Tools except maybe needing a little more margin below the "command args" control.

**Comment by d2phap** [comment] 2023-07-25 15:55
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)

**Closed as completed by d2phap** 2023-07-25 15:55 UTC
Labels: 🐞 bug
