### ISSUE TITLE
Reading .CBRs doesn't work

### ISSUE THREAD

**Issue by Troceleng** [d2phap/ImageGlass#1001] opened 2021-03-16 01:17 UTC
- Lower high-end desktop PC
 - Windows OS version: 10
 - ImageGlass version: 8.1.1.29

1. Zip pictures into a .7zip
2. Rename that .7zip into a .CBR
3. Attempt to open with ImageGlass
4. Blank screen

When I try to open a .CBR file (Comic Book Archive file), only a blank screen comes up. This isn't pleasant as I would like to read my comics.

When opening a .cbr with Windows Photos and Honeyview, I can freely read through the archive. It's an efficient way to store and move sets of digitized comicbooks and manga.

The lack of ability to read .CBRs is one of the only reasons I keep an image viewer other than ImageGlass on my PC. I would be happy if this ability was implemented.

**Comment by fire-eggs** [comment] 2021-03-16 01:47
Duplicate of issue #254

**Closed as completed by fire-eggs** 2021-03-16 01:47 UTC
Labels: 🎯 feature
