### ISSUE TITLE
Feature to assign keys of our liking to the navigation functions.

### ISSUE THREAD

**Issue by KaveeHana** [d2phap/ImageGlass#803] opened 2020-06-24 14:56 UTC
### Is your feature request related to a problem? Please describe.
Can't navigate easily using the left hand. (The right hand is doing it's business below the keyboard, if you know what I mean)

### Describe the solution you'd like
Ability to assign keys of our liking to the previous image, next image function

### Describe alternatives you've considered
Make it easier to navigate easier using the left hand.

**Comment by fire-eggs** [comment] 2020-07-26 21:22
Duplicate of issue #729

**Closed by fire-eggs** 2020-07-26 21:22 UTC
Labels: ✨ feature request, 📝 duplicate
