### ISSUE TITLE
Imageglass not displaying first image since update

### ISSUE THREAD

**Issue by derFleder** [d2phap/ImageGlass#1032] opened 2021-04-28 18:37 UTC
### System information:
 - Windows OS version: Windows 10 Pro 64bit latest Patch
 - ImageGlass version: 8.1.4.18

### To Reproduce
1. click on image file without imageglass window open
2. no image will be displayed

### Actual behavior:
Imageglass does not display the first image upon starting.
You have to scroll/switch to the next image and back to make it appear.
It only displays "First Picture reached" for 2 seconds and then nothing.
The image type does not matter, or the location.

### Expected behavior:
to display the picture

### Screenshots:
it just shows an empty Imageglass Window

**Comment by fire-eggs** [comment] 2021-04-28 18:48
Duplicate of issue #1019. A fix is available in the latest [ImageGlass MOON](https://imageglass.org/upload/moon/ImageGlass_Moon_8.1.4.28_x64.zip).

**Closed as completed by fire-eggs** 2021-04-28 18:48 UTC
