### ISSUE TITLE
After update to 8.1.4.18  the viewer shows a black screen with the leyend "reached the last image"

### ISSUE THREAD

**Issue by FabianToledo** [d2phap/ImageGlass#1044] opened 2021-05-08 19:16 UTC
### System information:
 - Windows OS version: 	10.0.19042 Build 19042
 - ImageGlass version:  8.1.4.18 

### To Reproduce
1. Double click on an image
2. 
3. 
4. 

### Actual behavior:
After update to 8.1.4.18 when I try to view an image double-clicking on it, the viewer shows a black screen with the leyend "reached the last image"
If there are more images in the folder I can view it pressing the "view next (or previous) image" button but If that image is the only one in the folder I can not do anything to view it. 

### Expected behavior:
View the clicked image

**Comment by fire-eggs** [comment] 2021-05-08 20:43
This is a duplicate of #1019, and fixed in the latest build of ImageGlass Moon https://imageglass.org/moon
The official release will be shipped in few weeks

**Closed as completed by fire-eggs** 2021-05-08 20:43 UTC
Labels: 🐞 bug
