### ISSUE TITLE
Show image properties "Exif, Xmp, Iptc, ..." tool

### ISSUE THREAD

**Issue by vvv-easy** [d2phap/ImageGlass#751] opened 2020-04-22 18:39 UTC
### Is your feature request related to a problem? Please describe.
Today Imageglass only shows the image file properties of the Windows.

### Describe the solution you'd like

It would be very interesting to also see the properties "Exif, Xmp, Iptc, ..."

### Describe alternatives you've considered

An easy way to implement it would be to use the application "command in line" ExifTool by Phil Harvey and show the console output.

**Comment by fire-eggs** [comment] 2020-07-26 21:21
duplicate of issue #661

**Comment by d2phap** [comment] 2020-08-12 06:55
merge this to #336

**Closed by d2phap** 2020-08-12 06:55 UTC
Labels: ✨ feature request, 📝 duplicate

**Comment by d2phap** [comment] 2020-09-27 13:58
Implemented Exif tool in ImageGlass Moon: https://imageglass.org/moon
For more details, check at #871
