### ISSUE TITLE
ImageGlass process(es) sometimes stays open and hogs CPU after closing app

### ISSUE THREAD

**Issue by shoebillanon** [d2phap/ImageGlass#1294] opened 2022-02-22 23:50 UTC
No idea how to replicate this but sometimes ImageGlass' process will stay active in the background after closing the app and hog about 30% of my CPU. This can happen multiple times too, resulting in multiple processes hogging 30% CPU each. I just updated from 8.2 to 8.5 and thought the bug was gone but nope.

**Comment by fire-eggs** [comment] 2022-02-23 01:10
Off-hand do you recall if the thumbnail bar was visible at the time of closing? Or did you edit (crop/rotate) the file you were looking at when you closed?

[These are the likeliest things I can think of off-hand which might be still running in the background at exit.]

**Comment by shoebillanon** [comment] 2022-02-23 17:40
Nope, neither. Was just looking at images and that is it.

**Comment by fire-eggs** [comment] 2022-02-28 14:50
I've yet to see the "hogging 30% of the CPU" issue, but I was able to get IG to have three background processes running with 8.5.1.22.

1. No IG background process.
2. Run IG. In settings, _check_ "continue running background"; save. Exit IG.
3. Note there is an IG background process.
4. Run IG. In settings, _uncheck_ "continue running background"; save. Exit IG.
5. Note there is still an IG background process. **[Bug!]**
6. Run IG. In settings, _check_ "continue running background"; save. Exit IG.
7. There are now two IG background processes. **[Bug!]**
8. Run IG. Make sure that "allow multiple instances" option is OFF. After that, when exiting IG, there are now three background IG processes. **[Bug!]** Also, running IG at this point does not show the welcome picture, even though that setting is on. [Bug?]

Turning off the "background" option in IG, and _not_ checking "Start with OS", then a reboot or re-login will probably be required to clear all background processes. [Or killing them manually via Task Manager.]

As far as the 30% CPU issue, I'm still investigating, but make sure that "check for update automatically" is _not_ selected when running IG.

**Comment by fire-eggs** [comment] 2022-02-28 15:09
One thing that occurs to me: when IG is "closed", the current FileWatcher doesn't appear to be stopped. I believe this means the IG background process is still watching the last viewed image folder. If that folder is "active" then IG could spend some cycles processing changes which aren't being viewed.

**Comment by Sxderp** [comment] 2022-03-08 21:04
This is somewhat tangential, but you mentioned it in your reproduction steps, how is "allow multiple instances" supposed to work with "continue running in background"? To me they seem mutually exclusive.

The only way I can see them working together is if ImageGlass used multiple windows for viewing images. The code isn't really conducive to this, when looking at it there seems to be an assumption that the process only has one viewport window.

**Comment by d2phap** [comment] 2022-04-27 14:59
If it has multiple instances, only the last instance will be kept running.

You can see the implementation below:
https://github.com/d2phap/ImageGlass/blob/7c416b299c2b5bf9f4acbc4c603a41e68fa64047/Source/ImageGlass/frmMain.cs#L3246-L3272

**Comment by d2phap** [comment] 2023-12-14 08:02
Should not an issue with v9

**Closed as completed by d2phap** 2023-12-14 08:02 UTC
Labels: 🐞 bug
