### ISSUE TITLE
Image corruption after editing/cropping an image

### ISSUE THREAD

**Issue by banshee24** [d2phap/ImageGlass#1134] opened 2021-09-06 08:56 UTC
### System information:
 - Windows OS version: Win10 Pro 20H2
 - ImageGlass version: 8.2.6.6

### Actual behavior:
after editing/cropping an image, thumbnail picture of the image is not refreshed

### Expected behavior:
new thumbnail image should be refreshed as edited image

### Screenshots:
https://pasteboard.co/Kjk2P6O.png
https://pasteboard.co/Kjk3aVJ.png

**Comment by fire-eggs** [comment] 2021-09-06 11:45
Probable duplicate of #1059 or #754 

Please let us know if the "Preserve Modify Date on Save" setting is enabled.

**Comment by banshee24** [comment] 2021-10-24 07:40
Hello,

"Preserve Modify Date on Save" setting is enabled and I still have the same problem. I hope that problem will be solved at upcoming versions.

Kind regards



B. Göktürk Bindal

Pilot CPL(A), FI(A)
B.Sc. Mech. Eng.

**Comment by fire-eggs** [comment] 2021-10-24 17:06
_Enabling_ the "Preserve Modify Date on Save" is what is causing the problem. Windows Explorer will only update the thumbnail when the modify date is _changed_.

[Modified your reply to remove your phone #]

**Comment by banshee24** [comment] 2021-10-24 17:26
I disabled that option now but when I edit the image and close the program it corrupts the image irreversibly. If I use 'save as' option for the edited image, new saved file kept good without any problems but original file corrupts again.


B. Göktürk Bindal

Pilot CPL(A), FI(A)
B.Sc. Mech. Eng.


Phone: +90 532 415 67 77

________________________________

**Comment by fire-eggs** [comment] 2021-10-25 14:38
OK, that sounds like a nasty problem! I'll take a look. For completeness, could you tell me what file format the original image is in? (png, jpeg, etc) Thanks!

**Comment by banshee24** [comment] 2021-10-25 15:10
Very strange, now it works both with .JPG and .PNG . I think it started to work after rebooting my PC. Btw I found another bug about that. That bug behaves differently both on JPG and PNG; For .JPG if you close the photo quickly just after editing the photo, it corrupts the file permanently, but if you wait just a bit after editing and then close the program it does not corrupt the file. For PNG; if you close the program quickly after editing, it just does not apply the changes on file. Here is my system;

[cid:c2c64fda-5667-4c75-a26b-98093f2d80b8]

May I also send you suggestions time to time in terms of design or you are working on just debugging? I really enjoy using this program, its pure design and availability of interface personalization is really cool. 🙂



B. Göktürk Bindal

Pilot CPL(A), FI(A)
B.Sc. Mech. Eng.


Phone: +90 532 415 67 77

________________________________

**Comment by fire-eggs** [comment] 2021-10-25 23:00
> For .JPG if you close the photo quickly just after editing the photo, it corrupts the file permanently, but if you wait just a bit after editing and then close the program it does not corrupt the file. For PNG; if you close the program quickly after editing, it just does not apply the changes on file.

Sorry for the late reply, my day went all sideways.

I've not had a chance to dig into the details, but what you describe matches what I recall. The process of saving a file is not currently coordinated with app shutdown. This means IG can shut down during the middle of saving the file, resulting in corruption or no output.

Waiting a little bit after editing the file before closing IG should work. Apparently, "preserve modify date on save" also solves the problem, but I don't yet know why!  I'll poke at this when I have a chance, you should use one of the workarounds in the meantime ...

>May I also send you suggestions time to time in terms of design or you are working on just debugging? I really enjoy using this program, its pure design and availability of interface personalization is really cool.

Thanks, and glad to hear it! 

I have no objection to reading your design suggestions, might provide me with some inspiration. Feel free to open an issue containing your thoughts. It'll be up to @d2phap to decide if anything is incorporated.

**Comment by fire-eggs** [comment] 2021-11-20 15:36
Recently posted to ImageGlass+ group:

>Warning: ImageGlas destroys images if saving after editing set and viewer scolled  forwards and backwards shortly after editing! 

Again, the same problem: image save is asynchronous but not coordinated. By navigating backward, the user is hitting the image during the save, causing file corruption.

**Comment by gsokoll** [comment] 2022-01-04 03:37
How about disabling the navigation buttons while saving is underway?  I've had the unpleasant experience of several images being irreversibly corrupted by this bug.  ImageGlass now uninstalled...

**Comment by d2phap** [comment] 2022-01-12 14:55
Please try the latest build of IG Moon which is to attempts to fix this issue.
https://imageglass.org/moon
Note that, the thumbnail bar is flashing when the app is busy, I will fix later.

**Closed as completed** 2022-01-16 02:35 UTC
Labels: 🐞 bug, 👌🏻 ready
