### ISSUE TITLE
image order didn't respect the setting, always ordered by name

### ISSUE THREAD

**Issue by xyzDist** [d2phap/ImageGlass#1747] opened 2023-12-03 00:48 UTC
### System information:
 - Windows OS version:  win10
 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. in setting no matter what you change to the order, it always show images by name order

### Actual behavior:
if I change to by date created, it should display images order by the setting correctly.
image order didn't respect the setting, always ordered by name

**Comment by d2phap** [comment] 2023-12-03 03:32
@xyzDist Can you send a video please? I cannot reproduce

**Comment by SanicTK2** [comment] 2023-12-04 17:49
I can reproduce this also with the same version and OS.
In the video you can see that I have set the last write time as the sort order, and the folder is also sorted in last write time ascending order. However, it is still going through images by ascending name order, as you can see after the first 3 images (2023/05/01, starting with letter m), it jumps to the last image in the folder (2023/5/12, starting with letter o).

https://github.com/d2phap/ImageGlass/assets/104337041/6680023d-cd6d-4325-89a3-b86c22afbe09

I've also included the testing images shown in the video.

[test.zip](https://github.com/d2phap/ImageGlass/files/13549626/test.zip)

**Comment by xyzDist** [comment] 2023-12-07 13:56
Thanks @SanicTK2 ! @d2phap, I experienced the same, would be great if you have time to look into it, thanks!

**Comment by d2phap** [comment] 2023-12-10 11:28
Thanks for the video, I found the code causes that issue. Will be fix in the next release

**Comment by ghost** [comment] 2023-12-11 14:20
Thank you for the fix! I have this issue as well in 9.0.8.1208_x64. Waiting on new update now.

**Comment by d2phap** [comment] 2023-12-28 11:15
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)

**Closed as completed by d2phap** 2023-12-28 11:15 UTC
Labels: 🐞 bug, 👌🏻 ready
